import pokemon from './gen1_5';
import {
  Category,
  AllPokemon,
  ThemeTemplate,
  Game,
  GameName,
  Pokemon,
} from './app/lib/definitions';

type Themes = {
  [name: string]: {
    name: string;
    identifier: string;
    names: string[];
  };
};

export const categories = [
  {
    name: 'Misc',
    language: 'EN',
    themes: [
      {
        identifier: 'colors',
        name: 'Colors',
        names: [
          'Azure',
          'Black',
          'Blue',
          'Brown',
          'Crimson',
          'Cyan',
          'Gold',
          'Green',
          'Indigo',
          'Ivory',
          'Jade',
          'Lavender',
          'Lilac',
          'Magenta',
          'Maroon',
          'Olive',
          'Orange',
          'Pink',
          'Purple',
          'Red',
          'Scarlet',
          'Silver',
          'Teal',
          'Turquoise',
          'White',
          'Amber',
          'Amethyst',
          'Aqua',
          'Blush',
          'Bronze',
          'Burgundy',
          'Canary',
          'Cerulean',
          'Charcoal',
          'Coral',
          'Emerald',
          'Fuchsia',
          'Garnet',
          'Hazel',
          'Mahogany',
          'Mint',
          'Peach',
          'Periwinkle',
          'Ruby',
          'Saffron',
          'Sapphire',
          'Sepia',
          'Topaz',
          'Vermilion',
          'Honeydew',
        ],
      },
      {
        identifier: 'emotions',
        name: 'Emotions',
        names: [
          'Joy',
          'Sadness',
          'Anger',
          'Fear',
          'Surprise',
          'Love',
          'Anxiety',
          'Pride',
          'Guilt',
          'Hope',
          'Envy',
          'Relief',
          'Shame',
          'Despair',
          'Ecstasy',
          'Bliss',
          'Awe',
          'Grief',
          'Euphoria',
          'Chaos',
          'Trust',
          'Peace',
          'Zeal',
          'Charm',
          'Pity',
          'Rage',
          'Lust',
          'Glee',
          'Doubt',
          'Mirth',
          'Panic',
          'Rapture',
          'Elation',
          'Fury',
          'Sorrow',
          'Hate',
          'Shyness',
          'Shock',
        ],
      },
    ],
  },
  {
    name: 'Food',
    language: 'EN',
    themes: [
      {
        identifier: 'food',
        name: 'Food',
        names: [
          'BBQ',
          'Biscuit',
          'Burger',
          'Calzone',
          'Casserole',
          'Chowder',
          'Cornbread',
          'Curry',
          'Dango',
          'Dumpling',
          'Eggroll',
          'Falafel',
          'Frittata',
          'Fudge',
          'Gumbo',
          'Hotcake',
          'Lasagna',
          'Meatball',
          'Muffin',
          'Omelette',
          'Pancake',
          'Pasta',
          'Pastry',
          'Pavlova',
          'Pizza',
          'Polenta',
          'Popcorn',
          'Pretzel',
          'Quiche',
          'Risotto',
          'Salami',
          'Sausage',
          'Shawarma',
          'Skewer',
          'Soup',
          'Souvlaki',
          'Spaghetti',
          'Steak',
          'Stew',
          'Sushi',
          'Taco',
          'Tempura',
          'Tiramisu',
          'Toast',
          'Toffee',
          'Tortilla',
          'Waffle',
          'Wonton',
          'Yakitori',
        ],
      },
    ],
  },
  {
    name: 'Mythology',
    language: 'EN',
    themes: [
      {
        identifier: 'norse-mythology',
        name: 'Norse Mythology',
        names: [
          'Thor',
          'Freya',
          'Loki',
          'Odin',
          'Baldr',
          'Frigg',
          'Tyr',
          'Saga',
          'Eir',
          'Skadi',
          'Sif',
          'Hel',
          'Vidar',
          'Njord',
          'Idun',
          'Fenrir',
          'Freyr',
          'Heimdall',
          'Ran',
          'Hermod',
          'Bragi',
          'Forseti',
          'Gerda',
          'Hoder',
          'Hodur',
          'Magni',
          'Modi',
          'Sigyn',
          'Sleipnir',
          'Sol',
          'Vali',
          'Ve',
          'Vili',
          'Angrboda',
          'Alviss',
          'Edda',
          'Fafnir',
          'Grid',
          'Hati',
          'Hlin',
          'Jord',
          'Mimir',
          'Nerthus',
          'Skoll',
          'Thrud',
          'Ullr',
          'Var',
          'Ymir',
        ],
      },
      {
        identifier: 'greek-mythology',
        name: 'Greek Mythology',
        names: [
          'Zeus',
          'Hera',
          'Poseidon',
          'Demeter',
          'Athena',
          'Apollo',
          'Artemis',
          'Ares',
          'Hermes',
          'Dionysus',
          'Persephone',
          'Hades',
          'Perseus',
          'Jason',
          'Odysseus',
          'Achilles',
          'Theseus',
          'Orpheus',
          'Icarus',
          'Medusa',
          'Circe',
          'Pandora',
          'Electra',
          'Echo',
          'Narcissus',
          'Pan',
          'Atlas',
          'Hector',
          'Paris',
          'Helen',
          'Cassandra',
          'Ariadne',
          'Calypso',
          'Nike',
          'Iris',
          'Hestia',
          'Eros',
          'Chaos',
          'Chiron',
          'Eurus',
          'Selene',
          'Triton',
          'Uranus',
          'Cronus',
          'Rhea',
          'Gaia',
          'Phoebe',
          'Janus',
        ],
      },
      {
        identifier: 'egyptian-mythology',
        name: 'Egyptian Mythology',
        names: [
          'Ra',
          'Isis',
          'Osiris',
          'Horus',
          'Anubis',
          'Thoth',
          'Bastet',
          'Sekhmet',
          'Set',
          'Amun',
          'Nut',
          'Maat',
          'Ptah',
          'Hathor',
          'Anhur',
          'Khnum',
          'Wadjet',
          'Sobek',
          'Bast',
          'Anuket',
          'Atum',
          'Neith',
          'Khonsu',
          'Mut',
          'Tefnut',
          'Khepri',
          'Seshat',
          'Serapis',
          'Nephthys',
          'Hapi',
          'Apis',
          'Osiris',
          'Horus',
          'Anubis',
          'Thoth',
          'Bastet',
          'Sekhmet',
          'Set',
          'Amun',
          'Nut',
          'Maat',
          'Ptah',
          'Hathor',
          'Anhur',
          'Khnum',
          'Wadjet',
          'Sobek',
          'Bast',
          'Anuket',
        ],
      },
      {
        identifier: 'polynesian-mythology',
        name: 'Polynesian Mythology',
        names: [
          'Maui',
          'Tane',
          'Pele',
          'Hina',
          'Kane',
          'Kanaloa',
          'Mahuika',
          'Whiro',
          'Tawhiri',
          'Rongo',
          'Tangaroa',
          'Haumia',
          'Papa',
          'Rangi',
        ],
      },
      {
        identifier: 'roman-mythology',
        name: 'Roman Mythology',
        names: [
          'Jupiter',
          'Juno',
          'Neptune',
          'Minerva',
          'Mars',
          'Venus',
          'Apollo',
          'Diana',
          'Mercury',
          'Vulcan',
          'Ceres',
          'Bacchus',
          'Proserpina',
          'Pluto',
          'Vesta',
          'Aeneas',
          'Remus',
          'Romulus',
          'Cupid',
          'Faunus',
          'Janus',
          'Juturna',
          'Latona',
          'Lucina',
          'Quirinus',
          'Saturn',
          'Silvanus',
          'Terminus',
          'Ops',
          'Flora',
          'Pomona',
          'Fides',
          'Lares',
          'Manes',
          'Genius',
          'Nona',
          'Decima',
          'Morta',
          'Carmenta',
          'Egeria',
          'Pales',
          'Pax',
          'Victoria',
          'Bellona',
          'Concordia',
          'Liber',
          'Salus',
        ],
      },
    ],
  },
  {
    name: 'Locations',
    language: 'EN',
    themes: [
      {
        identifier: 'countries',
        name: 'Countries',
        names: [
          'Japan',
          'Brazil',
          'Canada',
          'Mexico',
          'France',
          'Germany',
          'Italy',
          'Spain',
          'China',
          'India',
          'Russia',
          'Egypt',
          'Greece',
          'Turkey',
          'Norway',
          'Sweden',
          'Denmark',
          'Finland',
          'Iceland',
          'Ireland',
          'Poland',
          'Portugal',
          'Belgium',
          'Austria',
          'Argentina',
          'Chile',
          'Peru',
          'Colombia',
          'Australia',
          'New Zealand',
          'South Korea',
          'Vietnam',
          'Thailand',
          'Indonesia',
          'Malaysia',
          'Singapore',
          'Pakistan',
          'Iran',
          'Iraq',
          'Israel',
          'Jordan',
          'Lebanon',
          'Syria',
          'Kuwait',
          'Qatar',
        ],
      },
      {
        identifier: 'us-states',
        name: 'U.S States',
        names: [
          'California',
          'Texas',
          'Florida',
          'New York',
          'Ohio',
          'Georgia',
          'Michigan',
          'Virginia',
          'Arizona',
          'Tennessee',
          'Indiana',
          'Missouri',
          'Maryland',
          'Wisconsin',
          'Colorado',
          'Minnesota',
          'Alabama',
          'Louisiana',
          'Kentucky',
          'Oregon',
          'Oklahoma',
          'Iowa',
          'Arkansas',
          'Utah',
          'Nevada',
          'Kansas',
          'Nebraska',
          'Idaho',
          'Hawaii',
          'Maine',
          'Montana',
          'Delaware',
          'Vermont',
        ],
      },
      {
        identifier: 'islands',
        name: 'Islands',
        names: [
          'Bahamas',
          'Fiji',
          'Hawaii',
          'Jamaica',
          'Bali',
          'Maldives',
          'Samoa',
          'Borneo',
          'Tahiti',
          'Cuba',
          'Santorini',
          'Corsica',
          'Sicily',
          'Ibiza',
          'Crete',
          'Malta',
          'Cyprus',
          'Tonga',
          'Lombok',
          'Capri',
          'Rhodes',
          'Aruba',
          'Montserrat',
          'Antigua',
          'Curacao',
          'Martinique',
          'Guadeloupe',
          'Mallorca',
          'Ibiza',
          'Dominica',
          'Grenada',
        ],
      },
      {
        identifier: 'biomes',
        name: 'Biomes',
        names: [
          'Tundra',
          'Ocean',
          'Savannah',
          'Desert',
          'Grassland',
          'Taiga',
          'Rainforest',
          'Marsh',
          'Swamp',
          'Mountain',
          'Forest',
          'Jungle',
          'Steppe',
          'Prairie',
          'Plateau',
          'Canyon',
          'Delta',
          'Mangrove',
          'Lagoon',
          'Fjord',
          'Estuary',
          'Coral Reef',
          'Volcano',
          'Glacier',
          'Atoll',
          'Cave',
          'Oasis',
          'Dune',
          'Cliff',
          'Bayou',
          'Pond',
          'Lake',
          'River',
          'Waterfall',
          'Bluff',
          'Fen',
          'Bog',
          'Moor',
          'Badlands',
          'Crag',
          'Gorge',
          'Hill',
          'Plain',
          'Peninsula',
          'Cove',
          'Channel',
          'Sinkhole',
          'Butte',
        ],
      },
      {
        identifier: 'cities',
        name: 'Cities',
        names: [
          'Tokyo',
          'Paris',
          'London',
          'Sydney',
          'Moscow',
          'Berlin',
          'Rome',
          'Dubai',
          'Bangkok',
          'Toronto',
          'Madrid',
          'Seoul',
          'Mumbai',
          'Cairo',
          'Venice',
          'Athens',
          'Lisbon',
          'Prague',
          'Vienna',
          'Amsterdam',
          'Hanoi',
          'Jakarta',
          'Chicago',
          'Shanghai',
          'Beijing',
          'Singapore',
          'Dublin',
          'Lagos',
          'Milan',
          'Lima',
          'Kiev',
          'New York',
          'Los Angeles',
          'San Diego',
          'Boston',
          'Miami',
          'Houston',
          'Dallas',
          'Seattle',
          'Denver',
          'Phoenix',
          'Atlanta',
          'Detroit',
          'Manchester',
          'Liverpool',
          'Bristol',
          'Leeds',
          'York',
          'Oxford',
          'Cambridge',
        ],
      },
      {
        identifier: 'astrology',
        name: 'Astrology',
        names: [
          'Aries',
          'Taurus',
          'Gemini',
          'Cancer',
          'Leo',
          'Virgo',
          'Libra',
          'Scorpio',
          'Capricorn',
          'Aquarius',
          'Pisces',
          'Sun',
          'Moon',
          'Mercury',
          'Venus',
          'Mars',
          'Jupiter',
          'Saturn',
          'Uranus',
          'Neptune',
          'Pluto',
          'Elements',
          'Fire',
          'Earth',
          'Air',
          'Water',
          'Qualities',
          'Cardinal',
          'Fixed',
          'Mutable',
          'Houses',
          'First',
          'Second',
          'Third',
          'Fourth',
          'Fifth',
          'Sixth',
          'Seventh',
          'Eighth',
          'Ninth',
          'Tenth',
          'Eleventh',
          'Twelfth',
          'Aspects',
          'Trine',
          'Square',
          'Opposition',
        ],
      },
    ],
  },
  {
    name: 'Human Names',
    language: 'EN',
    themes: [
      {
        identifier: 'us-presidents',
        name: 'U.S Presidents',
        names: [
          'Washington',
          'Adams',
          'Jefferson',
          'Madison',
          'Monroe',
          'Jackson',
          'Van Buren',
          'Harrison',
          'Tyler',
          'Polk',
          'Taylor',
          'Fillmore',
          'Pierce',
          'Buchanan',
          'Lincoln',
          'Grant',
          'Hayes',
          'Garfield',
          'Arthur',
          'Cleveland',
          'Harrison',
          'McKinley',
          'Roosevelt',
          'Taft',
          'Wilson',
          'Harding',
          'Coolidge',
          'Hoover',
          'Truman',
          'Eisenhower',
          'Kennedy',
          'Johnson',
          'Nixon',
          'Ford',
          'Carter',
          'Reagan',
          'Clinton',
          'Bush',
          'Obama',
          'Trump',
          'Biden',
        ],
      },
      {
        identifier: 'celebrities',
        name: 'Celebrities',
        names: [
          'Elvis',
          'Beyoncé',
          'Madonna',
          'Prince',
          'Cher',
          'Adele',
          'Drake',
          'Ariana',
          'Taylor',
          'Eminem',
          'Rihanna',
          'Shakira',
          'Monroe',
          'Streep',
          'Cruise',
          'Clooney',
          'Denzel',
          'Pitt',
          'Jolie',
          'Depp',
          'Lawrence',
          'DiCaprio',
          'Gaga',
          'Swift',
          'Kanye',
          'Lopez',
          'Bieber',
          'Stallone',
          'Hanks',
          'Perry',
          'Cyrus',
          'Lana',
          'Jolie',
          'Hathaway',
          'Damon',
          'Johansson',
          'Bale',
          'Diaz',
          'Hathaway',
          'Gosling',
          'Phoenix',
          'Kutcher',
          'Kidman',
          'Cavill',
          'Jackman',
          'Fox',
          'Gosling',
        ],
      },
      {
        identifier: 'historic-figures',
        name: 'Historic Figures',
        names: [
          'Newton',
          'Galileo',
          'Einstein',
          'Da Vinci',
          'Cleopatra',
          'Napoleon',
          'Gandhi',
          'Lincoln',
          'Churchill',
          'Mozart',
          'Tesla',
          'Columbus',
          'Marie Curie',
          'Socrates',
          'Nelson',
          'Confucius',
          'Plato',
          'Aristotle',
          'Bach',
          'Catherine',
          'Hemingway',
          'Tolkien',
          'Genghis',
          'Voltaire',
          'Washington',
          'Darwin',
          'Alexander',
          'Spartacus',
          'Copernicus',
          'Freud',
          'Rembrandt',
          'Beethoven',
          'Cicero',
          'Marx',
          'Nero',
          'Homer',
          'Pablo',
          'Remus',
          'Pocahontas',
          'Joan of Arc',
          'Attila',
          'Houdini',
          'Euler',
          'Houdini',
        ],
      },
      {
        identifier: 'athletes',
        name: 'Athletes',
        names: [
          'Jordan',
          'Ali',
          'Serena',
          'Federer',
          'Ronaldo',
          'Messi',
          'Tiger Woods',
          'Nadal',
          'Bolt',
          'Pele',
          'Neymar',
          'Beckham',
          'Mia Hamm',
          'Biles',
          'Frazier',
          'Nadia',
          'Rousey',
          'Phelps',
          'Gretzky',
          'Maradona',
          'Senna',
          'Sharapova',
          'Federer',
          'Ginobili',
          'Kobe',
          'Bolt',
          'Nadal',
          'Ali',
          'Brady',
          'Gehrig',
          'Marino',
          'Shaq',
          'Woods',
          'Zidane',
          'Djokovic',
          'Nash',
          'Pele',
          'Cristiano',
          'Magic',
          'Wade',
          'Graf',
          'Rodman',
          'Messi',
          'Curry',
          'Durant',
          'Murray',
        ],
      },
    ],
  },
];

export const themes: Themes = categories.reduce<Themes>((acc, category) => {
  category.themes.forEach((theme) => (acc[theme.identifier] = theme));
  return acc;
}, {});

export const allPokemon: AllPokemon = JSON.parse(JSON.stringify(pokemon));

export const typeColors = {
  normal: '#A8A878',
  fire: '#F08030',
  water: '#6890F0',
  electric: '#F8D030',
  grass: '#78C850',
  ice: '#98D8D8',
  fighting: '#C03028',
  poison: '#A040A0',
  ground: '#E0C068',
  flying: '#A890F0',
  psychic: '#F85888',
  bug: '#A8B820',
  rock: '#B8A038',
  ghost: '#705898',
  dragon: '#7038F8',
  dark: '#705848',
  steel: '#B8B8D0',
  fairy: '#EE99AC',
};

// export const exGame: Game = {
//   id: 1,
//   theme: 'us-presidents',
//   name: 'Fire Red',
//   box: createBaseBoxFromTheme(themes['us-presidents']),
// };
