import { Pokemon } from '../pokemon_data/definitions';
import { Category, Theme, ThemesObject } from './definitions';

//////////////////////////////////////////////
/////////       Misc Category     ////////////
//////////////////////////////////////////////

const t_colors: Theme = {
  identifier: 'colors',
  name: 'Colors',
  names: [
    'Azure',
    'Black',
    'Blue',
    'Brown',
    'Crimson',
    'Cyan',
    'Gold',
    'Green',
    'Indigo',
    'Ivory',
    'Jade',
    'Lavender',
    'Lilac',
    'Magenta',
    'Maroon',
    'Olive',
    'Orange',
    'Pink',
    'Purple',
    'Red',
    'Scarlet',
    'Silver',
    'Teal',
    'Turquoise',
    'White',
    'Amber',
    'Amethyst',
    'Aqua',
    'Blush',
    'Bronze',
    'Burgundy',
    'Canary',
    'Cerulean',
    'Charcoal',
    'Coral',
    'Emerald',
    'Fuchsia',
    'Garnet',
    'Hazel',
    'Mahogany',
    'Mint',
    'Peach',
    'Periwinkle',
    'Ruby',
    'Saffron',
    'Sapphire',
    'Sepia',
    'Topaz',
    'Vermilion',
    'Honeydew',
  ],
};

const t_emotions: Theme = {
  identifier: 'emotions',
  name: 'Emotions',
  names: [
    'Joy',
    'Sadness',
    'Anger',
    'Fear',
    'Surprise',
    'Love',
    'Anxiety',
    'Pride',
    'Guilt',
    'Hope',
    'Envy',
    'Relief',
    'Shame',
    'Despair',
    'Ecstasy',
    'Bliss',
    'Awe',
    'Grief',
    'Euphoria',
    'Chaos',
    'Trust',
    'Peace',
    'Zeal',
    'Charm',
    'Pity',
    'Rage',
    'Lust',
    'Glee',
    'Doubt',
    'Mirth',
    'Panic',
    'Rapture',
    'Elation',
    'Fury',
    'Sorrow',
    'Hate',
    'Shyness',
    'Shock',
  ],
};

const t_websites: Theme = {
  name: 'Websites',
  identifier: 'websites',
  names: [
    'Google',
    'Reddit',
    'Twitch',
    'Yahoo',
    'Bing',
    'Ask',
    'Quora',
    'Flickr',
    'AOL',
    'Vimeo',
    'eBay',
    'BBC',
    'CNN',
    'MSNBC',
    'Fox',
    'Hulu',
    'IMDb',
    'Zoom',
    'Zillow',
    'Paypal',
    'GitHub',
    'Slack',
    'Lyft',
    'Uber',
    'TikTok',
    'Spotify',
    'Pandora',
    'Skype',
    'Venmo',
    'Yelp',
    'Badoo',
    'Bumble',
    'WeChat',
    'Kakao',
    'LINE',
    'Viber',
    'Vine',
    'MeWe',
    'Plurk',
    'Stumble',
    'WordPress',
    'Blogger',
    'Tumblr',
    'Pinterest',
    'Mix',
    'Dribbble',
    'Discord',
    'Snapchat',
    'WhatsApp',
    'Telegram',
    'Trello',
    'Evernote',
    'Foursquare',
    'Meetup',
    'Goodreads',
    'Medium',
    'Behance',
    'DeviantArt',
    'SoundCloud',
    'Mixcloud',
    'Bandcamp',
    'Giphy',
    'Imgur',
    '9GAG',
    'BuzzFeed',
    'Chegg',
    'Udemy',
    'Coursera',
    'Khan',
    'Codecademy',
    'Duolingo',
    'Rosetta',
    'Skillshare',
    'Teachable',
    'Wattpad',
    'FanFiction',
    'AO3',
    'Fandom',
    'Wikia',
    'Twitch',
    'YouTube',
    'Netflix',
    'Prime',
    'Disney+',
    'HBO',
    'Showtime',
    'Starz',
    'Peacock',
    'Crave',
    'BritBox',
    'Paramount',
    'Shudder',
    'Curiosity',
    'Discovery',
    'Magellan',
    'Kanopy',
    'Mubi',
    'Dailymotion',
  ],
};

const t_apps: Theme = {
  name: 'Apps',
  identifier: 'apps',
  names: [
    'Snapchat',
    'Discord',
    'Spotify',
    'Tinder',
    'Twitter',
    'Uber',
    'YouTube',
    'Reddit',
    'Slack',
    'Zoom',
    'Venmo',
    'TikTok',
    'WhatsApp',
    'Hinge',
    'Signal',
    'Bumble',
    'Shazam',
    'WeChat',
    'Skype',
    'Trello',
    'Pinterest',
    'PayPal',
    'Instagram',
    'Messenger',
    'LinkedIn',
    'Netflix',
    'Waze',
    'Lyft',
    'DoorDash',
    'Gmail',
    'Outlook',
    'Evernote',
    'Dropbox',
    'Twitch',
    'eBay',
    'Amazon',
    'Kindle',
    'Fitbit',
    'Notion',
    'Asana',
    'Yelp',
    'Pandora',
    'SoundHound',
    'Audible',
    'Google',
    'Apple',
    'Facebook',
    'Quora',
    'Snap',
    'Clubhouse',
    'Telegram',
    'Zomato',
    'CashApp',
    'Robinhood',
    'N26',
    'Monzo',
    'Strava',
    'Nike',
    'MyFitness',
    'Duolingo',
    'Coursera',
    'Udemy',
    'KhanAcad',
    'Kahoot',
    'Flipgrid',
    'Minecraft',
    'AmongUs',
    'PUBG',
    'Roblox',
    'Fortnite',
    'CandyCrush',
    'TempleRun',
    'SubwaySur',
    'AngryBird',
    'WordsWF',
    'Tetris',
    'Sudoku',
    'Headspace',
    'Calm',
    'Smule',
    'Sing',
    'TuneIn',
    'Deezer',
    'Stitcher',
    'iHeart',
    'SoundCloud',
    'Anchor',
    'Podbean',
    'Buzzsprout',
    'RSSRadio',
    'Libsyn',
    'Castbox',
    'PocketCast',
    'Spreaker',
    'Breaker',
    'Overcast',
    'Simplecast',
    'ACast',
  ],
};

const t_ailments: Theme = {
  name: 'Ailments',
  identifier: 'ailments',
  names: [
    'Flu',
    'Cold',
    'Fever',
    'Cough',
    'Allergy',
    'Asthma',
    'Migraine',
    'Cancer',
    'Diabetes',
    'Ulcer',
    'Stroke',
    'Gout',
    'Anemia',
    'Arthritis',
    'Measles',
    'Mumps',
    'Tetanus',
    'Rabies',
    'Scabies',
    'Pox',
    'Jaundice',
    'Plague',
    'Malaria',
    'Cholera',
    'Leprosy',
    'Lupus',
    'Eczema',
    'Psoriasis',
    'Dengue',
    'Zika',
    'SARS',
    'MERS',
    'Polio',
    'Meningitis',
    'HIV',
    'AIDS',
    'Hepatitis',
    'Gonorrhea',
    'Syphilis',
    'Chickenpox',
    'Shingles',
    'Conjunctiva',
    'IBS',
    "Crohn's",
    'Epilepsy',
    "Parkinson's",
    "Alzheimer's",
    'Osteoporosis',
    'Glaucoma',
    'Cataract',
    'Bronchitis',
    'Pneumonia',
    'TB',
    'Whooping',
    'RSV',
    'Norovirus',
    'E. coli',
    'Salmonella',
    'Lyme',
    'Celiac',
    'Sprue',
    'Thalassemia',
    'SickleCell',
    'Hemophilia',
    'Cystic',
    'Fibrosis',
    'Hypothyroid',
    'Hyperthyroid',
    'Goiter',
    'Vitiligo',
    'Ringworm',
    'Herpes',
    'HPV',
    'Molluscum',
    'MRSA',
    'Toxoplasma',
    'Giardia',
    'Amoebiasis',
    'Trich',
    'Pinworm',
    'Ascariasis',
    'Hookworm',
    'Tapeworm',
    'Schisto',
    'Lymphoma',
    'Myeloma',
    'Melanoma',
    'Sarcoma',
    'Glioma',
    'Leukemia',
    'Carcinoma',
    'Myoma',
    'Fibroma',
    'Lipoma',
    'Adenoma',
    'Nodule',
    'Polyp',
    'Cyst',
    'Abscess',
    'Boil',
  ],
};

const t_animals: Theme = {
  name: 'Animals',
  identifier: 'animals',
  names: [
    'Tiger',
    'Lion',
    'Bear',
    'Wolf',
    'Fox',
    'Eagle',
    'Hawk',
    'Raven',
    'Crow',
    'Owl',
    'Snake',
    'Lizard',
    'Turtle',
    'Frog',
    'Toad',
    'Fish',
    'Shark',
    'Whale',
    'Dolphin',
    'Octopus',
    'Squid',
    'Crab',
    'Lobster',
    'Shrimp',
    'Scorpion',
    'Spider',
    'Ant',
    'Bee',
    'Butterfly',
    'Moth',
    'Dragonfly',
    'Ladybug',
    'Beetle',
    'Mantis',
    'Fly',
    'Mosquito',
    'Mule',
    'Horse',
    'Donkey',
    'Zebra',
    'Giraffe',
    'Elephant',
    'Rhino',
    'Hippo',
    'Buffalo',
    'Cow',
    'Bison',
    'Goat',
    'Sheep',
    'Pig',
    'Boar',
    'Deer',
    'Elk',
    'Moose',
    'Antelope',
    'Kangaroo',
    'Koala',
    'Panda',
    'Bear',
    'Monkey',
    'Gorilla',
    'Chimp',
    'Orangutan',
    'Sloth',
    'Bat',
    'Rat',
    'Mouse',
    'Squirrel',
    'Rabbit',
    'Hare',
    'Hedgehog',
    'Porcupine',
    'Badger',
    'Otter',
    'Beaver',
    'Seal',
    'SeaLion',
    'Walrus',
    'Penguin',
    'Parrot',
    'Eagle',
    'Hawk',
    'Falcon',
    'Ostrich',
    'Emu',
    'Pelican',
    'Swan',
    'Duck',
    'Goose',
  ],
};

const t_dog_breeds: Theme = {
  name: 'Dog Breeds',
  identifier: 'dog-breeds',
  names: [
    'Husky',
    'Labrador',
    'Retriever',
    'Poodle',
    'Bulldog',
    'Boxer',
    'Dalmatian',
    'Chihuahua',
    'Pug',
    'Beagle',
    'Rottweiler',
    'ShihTzu',
    'Doberman',
    'Corgi',
    'Schnauzer',
    'Collie',
    'GreatDane',
    'Akita',
    'Dachshund',
    'Greyhound',
    'Malamute',
    'Pomeranian',
    'Setter',
    'Shepherd',
    'Spaniel',
    'Terrier',
    'Whippet',
    'Bichon',
    'Mastiff',
    'Weimaraner',
    'Basset',
    'Cocker',
    'Samoyed',
    'Hound',
    'Papillon',
    'Borzoi',
    'Briard',
    'Elkhound',
    'Finnish',
    'Griffon',
    'Ibizan',
    'Keeshond',
    'Komondor',
    'Leonberg',
    'Lhasa Apso',
    'Lowchen',
    'Pointer',
    'Saluki',
    'Schipperke',
    'Shiba',
    'Vizsla',
    'Yorkshire',
  ],
};

const t_birds: Theme = {
  name: 'Birds',
  identifier: 'birds',
  names: [
    'Eagle',
    'Hawk',
    'Raven',
    'Crow',
    'Owl',
    'Falcon',
    'Sparrow',
    'Robin',
    'Jay',
    'Cardinal',
    'Bluejay',
    'Humming',
    'Swallow',
    'Swift',
    'Dove',
    'Pigeon',
    'Woodpeck',
    'Parrot',
    'Macaw',
    'Cockatoo',
    'Canary',
    'Finch',
    'Toucan',
    'Pelican',
    'Albatross',
    'Seagull',
    'Penguin',
    'Ostrich',
    'Emu',
    'Flamingo',
    'Swan',
    'Goose',
    'Duck',
    'Egret',
    'Stork',
    'Heron',
    'Crane',
    'Ibis',
    'Kiwi',
    'Magpie',
    'Mynah',
    'Starling',
    'Thrasher',
    'Quail',
    'Cockatiel',
    'Lark',
    'Grebe',
    'Puffin',
    'Kingfisher',
    'Osprey',
    'Kite',
    'Goshawk',
    'Sparrow',
    'Bluebird',
    'Eagle',
  ],
};

const t_fish: Theme = {
  name: 'Fish',
  identifier: 'fish',
  names: [
    'Shark',
    'Whale',
    'Dolphin',
    'Tuna',
    'Salmon',
    'Trout',
    'Cod',
    'Bass',
    'Perch',
    'Pike',
    'Carp',
    'Catfish',
    'Guppy',
    'Goldfish',
    'Angelfish',
    'Swordfish',
    'Marlin',
    'Mackerel',
    'Herring',
    'Sardine',
    'Anchovy',
    'Eel',
    'Sturgeon',
    'Piranha',
    'Barracuda',
    'Mullet',
    'MahiMahi',
    'Halibut',
    'Flounder',
    'Sole',
    'Grouper',
    'Tilefish',
    'Trigger',
    'Clownfish',
    'Tang',
    'Surgeon',
    'Butterfly',
    'Puffer',
    'Blowfish',
    'Octopus',
    'Squid',
    'Cuttlefish',
    'Shrimp',
    'Crab',
    'Lobster',
    'Oyster',
    'Clam',
    'Mussel',
    'Scallop',
    'Snail',
    'Barnacle',
    'Starfish',
    'SeaUrchin',
    'Jellyfish',
    'Sponge',
    'SeaCucumber',
    'Seahorse',
    'SeaDragon',
  ],
};

const t_bugs: Theme = {
  name: 'Bugs',
  identifier: 'bugs',
  names: [
    'Beetle',
    'Ant',
    'Spider',
    'Fly',
    'Mosquito',
    'Wasp',
    'Bee',
    'Butterfly',
    'Moth',
    'Dragonfly',
    'Ladybug',
    'Grasshop',
    'Cicada',
    'Cricket',
    'Centipede',
    'Millipede',
    'Scorpion',
    'Tarantula',
    'Tick',
    'Flea',
    'Earwig',
    'Praying',
    'Mantis',
    'Walking',
    'Stick',
    'Firefly',
    'Glowworm',
    'Beetle',
    'Stinkbug',
    'Dungbeetl',
    'Leafbug',
    'Waterbug',
    'Rhinocero',
    'Hercules',
    'Beetle',
    'Atlas',
    'Moth',
    'Silkmoth',
    'Luna',
    'Moth',
    'Swallowtail',
    'Caterpillar',
    'Worm',
    'Weevil',
    'Snail',
    'Slug',
    'Cockroach',
    'Cicada',
    'Antlion',
    'Pillbug',
    'Crab',
    'Louse',
    'Termite',
    'Aphid',
    'Hornet',
    'Grub',
    'Dobsonfly',
    'Mayfly',
    'Diving',
    'Beetle',
  ],
};

const t_occupations: Theme = {
  name: 'Occupations',
  identifier: 'occupations',
  names: [
    'Doctor',
    'Nurse',
    'Teacher',
    'Engineer',
    'Artist',
    'Actor',
    'Writer',
    'Singer',
    'Farmer',
    'Chef',
    'Police',
    'Lawyer',
    'Judge',
    'Firefighter',
    'Pilot',
    'Soldier',
    'Driver',
    'Dancer',
    'Designer',
    'Scientist',
    'Athlete',
    'Painter',
    'Musician',
    'Architect',
    'Carpenter',
    'Plumber',
    'Electric',
    'Gardener',
    'Librarian',
    'Tailor',
    'Mechanic',
    'Veterin',
    'Zookeeper',
    'Photographer',
    'Editor',
    'Journalist',
    'Director',
    'Producer',
    'Animator',
    'Consultant',
    'Advisor',
    'Economist',
    'Psycholog',
    'Therapist',
    'Physicist',
    'Biologist',
    'Chemist',
    'Geologist',
    'Historian',
    'Philosoph',
    'Sociolog',
    'Anthropol',
    'Linguist',
    'Mathemat',
    'Statistic',
    'Actuary',
    'Broker',
    'Banker',
    'Investor',
    'Trader',
    'Entrepre',
    'Marketer',
    'Salesman',
    'Consultor',
    'Publicist',
    'Accountant',
    'Auditor',
    'Bookkeep',
    'Reception',
    'Secretary',
    'Assistant',
    'Assistant',
    'Reporter',
    'Conductor',
    'Stewardess',
    'Trolley',
    'Brakeman',
    'Cabin',
    'Attendant',
    'Dispatcher',
    'Porter',
    'Agent',
    'Ambassador',
    'Director',
    'Bishop',
    'Nun',
    'Chaplain',
  ],
};

const t_technical_terms: Theme = {
  name: 'Technical Terms',
  identifier: 'technical-terms',
  names: [
    'Motherboard',
    'Bluetooth',
    'VPN',
    'USB',
    'Firewall',
    'Ethernet',
    'Router',
    'Gateway',
    'Server',
    'Client',
    'Database',
    'Cache',
    'Algorithm',
    'Encryption',
    'Decryption',
    'Compiler',
    'Debugger',
    'Framework',
    'Library',
    'API',
    'Interface',
    'Protocol',
    'DNS',
    'IPaddress',
    'Hostname',
    'Domain',
    'Subnet',
    'LAN',
    'WAN',
    'Internet',
    'Cloud',
    'Backup',
    'Restore',
    'Monitor',
    'Keyboard',
    'Mouse',
    'Scanner',
    'Printer',
    'Speaker',
    'Microphone',
    'Camera',
    'Modem',
    'Processor',
    'Memory',
    'Storage',
    'Harddisk',
    'SSD',
    'RAM',
    'Graphics',
    'GPU',
    'CPU',
    'BIOS',
    'Firmware',
    'Driver',
    'Pixel',
    'Resolution',
    'Bandwidth',
    'Latency',
    'Ping',
    'Packet',
  ],
};

const t_crimes: Theme = {
  name: 'Crimes',
  identifier: 'crimes',
  names: [
    'Theft',
    'Robbery',
    'Assault',
    'Murder',
    'Arson',
    'Fraud',
    'Forgery',
    'Extortion',
    'Kidnap',
    'Hijack',
    'Smuggle',
    'Embezzle',
    'Perjury',
    'Bribery',
    'Blackmail',
    'Stalking',
    'Vandalism',
    'Mugging',
    'Shoplift',
    'Harass',
    'Sabotage',
    'Espionage',
    'Launder',
    'Racketeer',
    'Felony',
    'Pyramid',
    'Battery',
    'Piracy',
    'Slander',
    'Libel',
    'Rob',
    'Pillage',
    'Drugs',
    'Theft',
    'Poach',
    'Fraud',
    'Graft',
    'Swindle',
    'Scam',
    'Rustle',
    'Bootleg',
    'Cheat',
    'Hack',
  ],
};

const t_general_brands: Theme = {
  name: 'General Brands',
  identifier: 'general-brands',
  names: [
    'Apple',
    'Microsoft',
    'Samsung',
    'Sony',
    'Google',
    'Toyota',
    'Honda',
    'Nike',
    'Adidas',
    'Puma',
    'Reebok',
    'Canon',
    'Nikon',
    'Panasonic',
    'LG',
    'Mitsubishi',
    'Bose',
    'Philips',
    'Dell',
    'HP',
    'Lenovo',
    'Acer',
    'Asus',
    'Alienware',
    'Fujitsu',
    'Toshiba',
    'Sharp',
    'JVC',
    'Hewlett',
    'Packard',
    'Corsair',
    'Western',
    'Digital',
    'Seagate',
    'Logitech',
    'SteelSeries',
    'Razer',
    'Vizio',
    'Brother',
    'Epson',
    'Xerox',
    'Lexmark',
    'Verizon',
    'ATandT',
    'Sprint',
    'T-Mobile',
    'Qualcomm',
    'Intel',
    'AMD',
    'ARM',
    'Cisco',
    'Linksys',
    'Netgear',
    'Belkin',
    'Ubiquiti',
    'Sennheiser',
    'Plantronics',
    'Garmin',
    'Western',
    'Union',
    'Mastercard',
    'Visa',
    'PayPal',
    'American',
    'Express',
    'Capital',
    'One',
    'HSBC',
    'Citibank',
    'Barclays',
    'TD',
    'Bank',
    'Scotiabank',
    'ING',
    'Credit',
    'Ameritrade',
    'Charles',
    'Schwab',
    'Fidelity',
    'Vanguard',
    'BlackRock',
    'Goldman',
    'Sachs',
    'Morgan',
    'Stanley',
    'UBS',
    'Deutsche',
    'Bank',
    'BNP',
    'Paribas',
    'Societe',
    'Generale',
    'UBS',
    'Nomura',
    'Merrill',
    'Lynch',
    'JPMorgan',
    'Chase',
  ],
};

const c_misc: Category = {
  name: 'Misc 🐶',
  language: 'EN',
  bgColor: '#00A96E',
  themes: [
    t_colors,
    t_emotions,
    t_websites,
    t_apps,
    t_ailments,
    t_animals,
    t_dog_breeds,
    t_birds,
    t_fish,
    t_bugs,
    t_occupations,
    t_technical_terms,
    t_crimes,
    t_general_brands,
  ],
};

//////////////////////////////////////////////
///////       Vegetation Category     ////////
//////////////////////////////////////////////

const t_plants: Theme = {
  name: 'Plants',
  identifier: 'plants',
  names: [
    'Rose',
    'Lily',
    'Daisy',
    'Tulip',
    'Poppy',
    'Sunflower',
    'Violet',
    'Jasmine',
    'Orchid',
    'Pansy',
    'Peony',
    'Iris',
    'Blossom',
    'Petunia',
    'Fern',
    'Lavender',
    'Holly',
    'Maple',
    'Juniper',
    'Birch',
    'Willow',
    'Cypress',
    'Alder',
    'Pine',
    'Acacia',
    'Bamboo',
    'Cedar',
    'Oak',
    'Ash',
    'Hazel',
    'Magnolia',
    'Rosemary',
    'Thyme',
    'Basil',
    'Sage',
    'Mint',
    'Lemon',
    'Cherry',
    'Apple',
    'Plum',
    'Pear',
    'Peach',
    'Fig',
    'Grape',
    'Kiwi',
    'Melon',
    'Cactus',
    'Aloe',
    'Dandelion',
    'Clover',
    'Moss',
    'Sequoia',
    'Ficus',
    'Palm',
    'Bonsai',
    'Lotus',
    'Hyacinth',
    'Mimosa',
    'Azalea',
    'Camellia',
    'Daffodil',
    'Gladiolus',
    'Marigold',
    'Narcissus',
    'Zinnia',
    'Carnation',
    'Dahlia',
    'Eucalyptus',
    'Gardenia',
    'Hibiscus',
    'Jasmine',
    'Lilac',
    'Magnolia',
    'Morning',
    'Glory',
    'Primrose',
    'Snapdragon',
    'Sweetpea',
    'Wisteria',
    'Yarrow',
    'Yucca',
  ],
};

const t_flowers: Theme = {
  name: 'Flowers',
  identifier: 'flowers',
  names: [
    'Rose',
    'Lily',
    'Daisy',
    'Tulip',
    'Poppy',
    'Sunflower',
    'Violet',
    'Jasmine',
    'Orchid',
    'Pansy',
    'Peony',
    'Iris',
    'Blossom',
    'Petunia',
    'Lavender',
    'Hollyhock',
    'Marigold',
    'Carnation',
    'Daffodil',
    'Dahlia',
    'Zinnia',
    'Camellia',
    'Gladiolus',
    'Magnolia',
    'Hyacinth',
    'Azalea',
    'Dandelion',
    'Freesia',
    'Geranium',
    'Lotus',
    'Morning',
    'Glory',
    'Primrose',
    'Snapdragon',
    'Sweetpea',
    'Wisteria',
    'Yarrow',
    'Begonia',
    'Clematis',
    'Fuchsia',
    'Hibiscus',
    'Lilac',
    'Nasturtium',
    'Anemone',
    'Bluebell',
    'Foxglove',
    'Jonquil',
    'Larkspur',
    'Snowdrop',
    'Thistle',
    'Verbena',
    'Aster',
    'Buttercup',
    'Cowslip',
    'Heather',
  ],
};

const t_trees: Theme = {
  name: 'Trees',
  identifier: 'trees',
  names: [
    'Oak',
    'Maple',
    'Birch',
    'Willow',
    'Cedar',
    'Pine',
    'Ash',
    'Alder',
    'Juniper',
    'Acacia',
    'Beech',
    'Cypress',
    'Elm',
    'Fir',
    'Hickory',
    'Mahogany',
    'Poplar',
    'Redwood',
    'Sycamore',
    'Spruce',
    'Walnut',
    'Cherry',
    'Chestnut',
    'Eucalyptus',
    'Hemlock',
    'Magnolia',
    'Palm',
    'Bamboo',
    'Baobab',
    'Bonsai',
    'Banyan',
    'Douglas',
    'Ficus',
    'Ginkgo',
    'Linden',
    'Mango',
    'Olive',
    'Papaya',
    'Rubber',
    'Sandalwood',
    'Teak',
    'Yew',
    'Zelkova',
    'Almond',
    'Avocado',
    'Buckeye',
    'Catalpa',
    'Dogwood',
    'Elder',
    'Hackberry',
    'Locust',
    'Mulberry',
    'Rowan',
    'Sassafras',
    'Tamarind',
    'Viburnum',
    'Wisteria',
    'Yucca',
  ],
};

const t_aquatic_plants: Theme = {
  name: 'Aquatic Plants',
  identifier: 'aquatic-plants',
  names: [
    'Seagrass',
    'Kelp',
    'Seaweed',
    'Algae',
    'Waterlily',
    'Cattail',
    'Duckweed',
    'Waterfern',
    'Watercress',
    'Pondweed',
    'Waterwort',
    'Coralwort',
    'Anemone',
    'Starwort',
    'Watermint',
    'Sealily',
    'Coralweed',
    'Sealwort',
    'Seagrass',
    'Algaegrass',
    'Seaweed',
    'Waterlily',
    'Cattail',
    'Duckweed',
    'Waterfern',
  ],
};

const c_vegetation: Category = {
  name: 'Vegetation 🌼',
  language: 'EN',
  bgColor: '#13A10E',
  themes: [t_plants, t_flowers, t_trees, t_aquatic_plants],
};

//////////////////////////////////////////////
/////////       Food Category     ////////////
//////////////////////////////////////////////

const t_food: Theme = {
  identifier: 'food',
  name: 'Food',
  names: [
    'BBQ',
    'Biscuit',
    'Burger',
    'Calzone',
    'Casserole',
    'Chowder',
    'Cornbread',
    'Curry',
    'Dango',
    'Dumpling',
    'Eggroll',
    'Falafel',
    'Frittata',
    'Fudge',
    'Gumbo',
    'Hotcake',
    'Lasagna',
    'Meatball',
    'Muffin',
    'Omelette',
    'Pancake',
    'Pasta',
    'Pastry',
    'Pavlova',
    'Pizza',
    'Polenta',
    'Popcorn',
    'Pretzel',
    'Quiche',
    'Risotto',
    'Salami',
    'Sausage',
    'Shawarma',
    'Skewer',
    'Soup',
    'Souvlaki',
    'Spaghetti',
    'Steak',
    'Stew',
    'Sushi',
    'Taco',
    'Tempura',
    'Tiramisu',
    'Toast',
    'Toffee',
    'Tortilla',
    'Waffle',
    'Wonton',
    'Yakitori',
  ],
};

const t_fruit: Theme = {
  name: 'Fruit',
  identifier: 'fruit',
  names: [
    'Apple',
    'Banana',
    'Cherry',
    'Grape',
    'Orange',
    'Mango',
    'Peach',
    'Pear',
    'Plum',
    'Kiwi',
    'Melon',
    'Papaya',
    'Lemon',
    'Lime',
    'Fig',
    'Grapefruit',
    'Apricot',
    'Pineapple',
    'Coconut',
    'Cranberry',
    'Blueberry',
    'Raspberry',
    'Strawberry',
    'Blackberry',
    'Watermelon',
    'Guava',
    'Lychee',
    'Nectarine',
    'Clementine',
    'Tangerine',
    'Starfruit',
    'Persimmon',
    'Cantaloupe',
    'Honeydew',
    'Mulberry',
    'Cherimoya',
    'Durian',
    'Figs',
    'Pears',
    'Apricots',
    'Custard',
    'Jelly',
    'Avocado',
    'Chili',
    'Mango',
    'Açaí',
    'Soursop',
    'Feijoa',
  ],
};

const t_veggies: Theme = {
  name: 'Veggies',
  identifier: 'veggies',
  names: [
    'Carrot',
    'Tomato',
    'Potato',
    'Broccoli',
    'Spinach',
    'Cabbage',
    'Pepper',
    'Lettuce',
    'Radish',
    'Onion',
    'Celery',
    'Pumpkin',
    'Zucchini',
    'Eggplant',
    'Cucumber',
    'Garlic',
    'Turnip',
    'Kale',
    'Beetroot',
    'Artichoke',
    'Asparagus',
    'Brussels',
    'Sprout',
    'Peas',
    'Mushroom',
    'Bean',
    'Squash',
    'Leek',
    'Yam',
    'Okra',
    'Rutabaga',
    'Fennel',
    'Ginger',
    'Chili',
    'Soybean',
    'Chard',
    'Bokchoy',
    'Endive',
    'Arugula',
    'Parsnip',
    'Scallion',
    'Chicory',
    'Jicama',
    'Lentil',
    'Mungbean',
    'Radish',
    'Salsify',
    'Skirret',
    'Taro',
    'Tatsoi',
    'Yardlong',
    'Zucchini',
  ],
};

const t_meats: Theme = {
  name: 'Meats',
  identifier: 'meats',
  names: [
    'Beef',
    'Pork',
    'Lamb',
    'Venison',
    'Chicken',
    'Turkey',
    'Duck',
    'Quail',
    'Goose',
    'Rabbit',
    'Bison',
    'Elk',
    'Boar',
    'Ostrich',
    'Emu',
    'Kangaroo',
    'Horse',
    'Lobster',
    'Crab',
    'Shrimp',
    'Cod',
    'Salmon',
    'Tuna',
    'Trout',
    'Bass',
    'Haddock',
    'Sardine',
    'Mackerel',
    'Anchovy',
    'Herring',
  ],
};

const t_condiments: Theme = {
  name: 'Condiments',
  identifier: 'condiments',
  names: [
    'Salt',
    'Pepper',
    'Mustard',
    'Ketchup',
    'Mayonnaise',
    'Soy Sauce',
    'Vinegar',
    'Honey',
    'Sriracha',
    'Relish',
    'Tabasco',
    'Wasabi',
    'BBQ Sauce',
    'Teriyaki',
    'Tartar',
    'Pesto',
    'Chutney',
    'Salsa',
    'Guacamole',
    'Hummus',
    'Aioli',
    'Marmite',
    'Kimchi',
    'Harissa',
    'Tahini',
  ],
};

const t_spices: Theme = {
  name: 'Spices',
  identifier: 'spices',
  names: [
    'Clove',
    'Cumin',
    'Paprika',
    'Cinnamon',
    'Saffron',
    'Nutmeg',
    'Ginger',
    'Cardamom',
    'Turmeric',
    'Chili',
    'Pepper',
    'Garlic',
    'Basil',
    'Thyme',
    'Rosemary',
    'Oregano',
    'Sage',
    'Parsley',
    'Dill',
    'Fennel',
    'Anise',
    'Caraway',
    'Chives',
    'Allspice',
    'Celery',
    'Mustard',
    'Sumac',
    'Tarragon',
    'Juniper',
    'Bay Leaf',
  ],
};

const t_sweets: Theme = {
  name: 'Sweets',
  identifier: 'sweets',
  names: [
    'Candy',
    'Cookie',
    'Brownie',
    'Muffin',
    'Fudge',
    'Toffee',
    'Caramel',
    'Truffle',
    'Bonbon',
    'Pudding',
    'Gelato',
    'Sorbet',
    'Sherbet',
    'Cupcake',
    'Macaron',
    'Eclair',
    'Donut',
    'Churro',
    'Tiramisu',
    'Mousse',
    'Pancake',
    'Waffle',
    'Scone',
    'Marshy',
    'Frosty',
    'Nougat',
    'ChocIce',
    'Cannoli',
    'Fondue',
    'Praline',
    'Gelato',
    'Biscuit',
    'Doughnut',
    'Frosting',
    'Jellybean',
    'Lollipop',
    'Macaroon',
    'Meringue',
    'Popsicle',
    'Snowcone',
    'Sorbet',
    'Souffle',
    'Sundae',
  ],
};

const t_candy: Theme = {
  name: 'Candy',
  identifier: 'candy',
  names: [
    'Candy',
    'Gummy',
    'Skittles',
    'Twizzler',
    'Snickers',
    'KitKat',
    'Reese',
    'Mentos',
    'Jellybean',
    'M&M',
    'Lollipop',
    'Tootsie',
    'SourPatch',
    'MilkyWay',
    'Nerds',
    'Peppermint',
    'Jawbreaker',
    'Bubblegum',
    'Licorice',
    'Smarties',
    'Caramel',
    'RockCandy',
    'PixyStix',
    'AlmondJoy',
    'PopRocks',
    'Pez',
    'SweeTarts',
    'CandyCorn',
    'Snickers',
    'Twix',
    'Gobstopper',
    'RingPop',
    'AirHead',
    'Dots',
    'HubbaBubba',
    'Warheads',
    'Hershey',
    'SourPatch',
  ],
};

const t_snacks: Theme = {
  name: 'Snacks',
  identifier: 'snack',
  names: [
    'Chip',
    'Pretzel',
    'Popcorn',
    'Nacho',
    'Cheetos',
    'Doritos',
    'Fritos',
    'CheezIt',
    'Ritz',
    'Oreo',
    'Twinkie',
    'Pringle',
    'Granola',
    'Raisin',
    'Peanut',
    'Cashew',
    'Pistachio',
    'Almonds',
    'Walnut',
    'Pecan',
    'Macadamia',
    'TrailMix',
    'Sunflower',
    'FruitSnack',
    'Fruit',
    'Leather',
    'BeefJerky',
    'RiceCake',
    'CerealBar',
    'PopTart',
    'FruitRollUp',
    'Graham',
    'AnimalCracker',
    'GranolaBar',
    'Pocky',
    'Nutella',
    'Gelatin',
    'Popsicle',
    'IceCream',
    'Sandwich',
    'Milkshake',
    'Yogurt',
    'Bagel',
    'Chips',
    'Fruit',
    'Cookie',
  ],
};

const t_cheese: Theme = {
  name: 'Cheese',
  identifier: 'cheese',
  names: [
    'Cheddar',
    'Gouda',
    'Brie',
    'Feta',
    'Parmesan',
    'Mozzarella',
    'Gorgonzola',
    'Camembert',
    'Colby',
    'Havarti',
    'Provolone',
    'Edam',
    'Fontina',
    'Ricotta',
    'Manchego',
    'Muenster',
    'Emmental',
    'Jarlsberg',
    'Pepperjack',
    'Gruyere',
    'GoatCheese',
    'BlueCheese',
    'Limburger',
  ],
};

const t_restaurants: Theme = {
  name: 'Restaurants',
  identifier: 'restaurants',
  names: [
    'McDonalds',
    'BurgerKing',
    'Starbucks',
    'Subway',
    'Wendys',
    'Chipotle',
    'TacoBell',
    'PizzaHut',
    'Dominos',
    'KFC',
    'Panera',
    'ChickFilA',
    'Dunkin',
    'FiveGuys',
    'PandaExprs',
    'InNOut',
    'Arbys',
    'JimmyJohns',
    'LittleCsrs',
    'JackBox',
    'CarlJr',
    'Cheesecake',
    'OliveGarden',
    'RedLobster',
    'BDubs',
    'LongJohns',
    'TexasRoad',
    'SaltGrass',
    'RedRobin',
    'Chilis',
    'RubyTuesday',
    'Outback',
    'Dennys',
    'PFChangs',
    'Applebees',
    'Carrabbas',
    'Bonefish',
    'YardHouse',
    'BahamaBree',
    'Maggianos',
    'Fogo',
    'Seasons52',
    'Brio',
    'OCharleys',
    'BJs',
  ],
};

const c_food: Category = {
  name: 'Food 🍟',
  language: 'EN',
  bgColor: '#F03A17',
  themes: [
    t_food,
    t_fruit,
    t_veggies,
    t_meats,
    t_condiments,
    t_spices,
    t_sweets,
    t_candy,
    t_snacks,
    t_cheese,
    t_restaurants,
  ],
};

//////////////////////////////////////////////
/////////       Drinks Category     //////////
//////////////////////////////////////////////

const t_drinks: Theme = {
  name: 'Drinks',
  identifier: 'drinks',
  names: [
    'Coffee',
    'Tea',
    'Latte',
    'Espresso',
    'Mocha',
    'Cappuccino',
    'Macchiato',
    'Americano',
    'Smoothie',
    'Juice',
    'Lemonade',
    'Soda',
    'Cola',
    'RootBeer',
    'Sprite',
    'Pepsi',
    'Mountain',
    'Dew',
    'Fanta',
    'Gatorade',
    'Powerade',
    'RedBull',
    'Monster',
    'Rockstar',
    'Juice',
    'Energy',
    'Drink',
    'Water',
    'Seltzer',
    'Beer',
    'Ale',
    'Lager',
    'Stout',
    'Porter',
    'Pilsner',
    'Wine',
    'Merlot',
    'Pinot',
    'Grigio',
    'Cabernet',
    'Sauvignon',
    'Champagne',
    'Mimosa',
    'Margarita',
    'Martini',
    'Whiskey',
    'Vodka',
  ],
};

const t_drink_brands: Theme = {
  name: 'Drink Brands',
  identifier: 'drink-brands',
  names: [
    'Coke',
    'Pepsi',
    'Sprite',
    'Fanta',
    'RedBull',
    'Monster',
    'Rockstar',
    'Gatorade',
    'Powerade',
    'Aquafina',
    'Dasani',
    'Evian',
    'Perrier',
    'SanPellegr',
    'Starbucks',
    'Nespresso',
    'Lipton',
    'Tropicana',
    'OceanSpray',
    'MinuteMaid',
    'Welchs',
    'VitaminWater',
    'Arizona',
    'Snapple',
    'Sobe',
    'Glaceau',
    'Xyience',
    'Propel',
    'Fuze',
  ],
};

const t_soda: Theme = {
  name: 'Soda',
  identifier: 'soda',
  names: [
    'Coke',
    'Pepsi',
    'Sprite',
    'Fanta',
    'DrPepper',
    'MountainDw',
    '7Up',
    'RootBeer',
    'Sunkist',
    'DietCoke',
    'CanadaDry',
    'Schweppes',
    'AandW',
    'MelloYellw',
    'PibbXtra',
    'Fresca',
    'Crush',
    'Barqs',
    'SierraMist',
    'Squirt',
    'BigRed',
    'CreamSoda',
    'SunDrop',
    'IBC',
    'CherryCoke',
    'RC',
    'Jones',
    'Shasta',
    'Jarritos',
    'Boylan',
  ],
};

const t_tea: Theme = {
  name: 'Tea',
  identifier: 'tea',
  names: [
    'GreenTea',
    'BlackTea',
    'Oolong',
    'WhiteTea',
    'EarlGrey',
    'ChaiTea',
    'JasmineTea',
    'Matcha',
    'HerbalTea',
    'Peppermint',
    'Chamomile',
    'Rooibos',
    'Genmaicha',
    'Hojicha',
    'Sencha',
    'PuErh',
    'YerbaMate',
    'Lapsang',
    'Assam',
  ],
};

const t_coffee: Theme = {
  name: 'Coffee',
  identifier: 'coffee',
  names: [
    'Espresso',
    'Latte',
    'Cappuccino',
    'Mocha',
    'Americano',
    'Macchiato',
    'FlatWhite',
    'Affogato',
    'Turkish',
    'Irish',
    'Vienna',
    'Doppio',
    'Ristretto',
    'Cortado',
    'Breve',
    'ColdBrew',
    'Instant',
    'Decaf',
    'Nitro',
    'Pourover',
    'Aeropress',
    'Espresso',
    'Lungo',
    'RedEye',
    'Cubano',
    'Phin',
  ],
};

const t_cocktails: Theme = {
  name: 'Cocktails',
  identifier: 'cocktails',
  names: [
    'Martini',
    'Margarita',
    'Daiquiri',
    'Mojito',
    'Cosmopoli',
    'Negroni',
    'Manhattan',
    'OldFashion',
    'MaiTai',
    'BloodyMary',
    'MoscowMule',
    'PinaColada',
    'Sazerac',
    'WhiskeySo',
    'Gimlet',
    'Bellini',
    'Caipirinha',
    'TomCollins',
    'Paloma',
    'Singapore',
    'Sling',
    'Sidecar',
    'Mimosa',
    'Martinez',
    'Julep',
    'Mule',
    'HotToddy',
    'Spritz',
  ],
};

const t_starbucks_drinks: Theme = {
  name: 'Starbucks Drinks',
  identifier: 'starbucks-drinks',
  names: [
    'Latte',
    'Cappuccino',
    'Macchiato',
    'Americano',
    'Mocha',
    'Espresso',
    'Teavana',
    'Refresher',
    'FlatWhite',
    'Nitro',
    'ColdBrew',
    'ChaiLatte',
    'IcedCoffee',
    'PikePlace',
    'Vanilla',
    'Caramel',
    'JavaChip',
    'GreenTea',
    'PinkDrink',
  ],
};

const c_drinks: Category = {
  name: 'Drinks 🍺',
  language: 'EN',
  bgColor: '#C98D43',
  themes: [t_drinks, t_drink_brands, t_soda, t_tea, t_coffee, t_cocktails, t_starbucks_drinks],
};

//////////////////////////////////////////////
///////       Mythology Category     /////////
//////////////////////////////////////////////

const t_norse_mythology: Theme = {
  identifier: 'norse-mythology',
  name: 'Norse Mythology',
  names: [
    'Thor',
    'Freya',
    'Loki',
    'Odin',
    'Baldr',
    'Frigg',
    'Tyr',
    'Saga',
    'Eir',
    'Skadi',
    'Sif',
    'Hel',
    'Vidar',
    'Njord',
    'Idun',
    'Fenrir',
    'Freyr',
    'Heimdall',
    'Ran',
    'Hermod',
    'Bragi',
    'Forseti',
    'Gerda',
    'Hoder',
    'Hodur',
    'Magni',
    'Modi',
    'Sigyn',
    'Sleipnir',
    'Sol',
    'Vali',
    'Ve',
    'Vili',
    'Angrboda',
    'Alviss',
    'Edda',
    'Fafnir',
    'Grid',
    'Hati',
    'Hlin',
    'Jord',
    'Mimir',
    'Nerthus',
    'Skoll',
    'Thrud',
    'Ullr',
    'Var',
    'Ymir',
  ],
};

const t_greek_mythology: Theme = {
  identifier: 'greek-mythology',
  name: 'Greek Mythology',
  names: [
    'Zeus',
    'Hera',
    'Poseidon',
    'Demeter',
    'Athena',
    'Apollo',
    'Artemis',
    'Ares',
    'Hermes',
    'Dionysus',
    'Persephone',
    'Hades',
    'Perseus',
    'Jason',
    'Odysseus',
    'Achilles',
    'Theseus',
    'Orpheus',
    'Icarus',
    'Medusa',
    'Circe',
    'Pandora',
    'Electra',
    'Echo',
    'Narcissus',
    'Pan',
    'Atlas',
    'Hector',
    'Paris',
    'Helen',
    'Cassandra',
    'Ariadne',
    'Calypso',
    'Nike',
    'Iris',
    'Hestia',
    'Eros',
    'Chaos',
    'Chiron',
    'Eurus',
    'Selene',
    'Triton',
    'Uranus',
    'Cronus',
    'Rhea',
    'Gaia',
    'Phoebe',
    'Janus',
  ],
};

const t_egyptian_mythology: Theme = {
  identifier: 'egyptian-mythology',
  name: 'Egyptian Mythology',
  names: [
    'Ra',
    'Isis',
    'Osiris',
    'Horus',
    'Anubis',
    'Thoth',
    'Bastet',
    'Sekhmet',
    'Set',
    'Amun',
    'Nut',
    'Maat',
    'Ptah',
    'Hathor',
    'Anhur',
    'Khnum',
    'Wadjet',
    'Sobek',
    'Bast',
    'Anuket',
    'Atum',
    'Neith',
    'Khonsu',
    'Mut',
    'Tefnut',
    'Khepri',
    'Seshat',
    'Serapis',
    'Nephthys',
    'Hapi',
    'Apis',
    'Osiris',
    'Horus',
    'Anubis',
    'Thoth',
    'Bastet',
    'Sekhmet',
    'Set',
    'Amun',
    'Nut',
    'Maat',
    'Ptah',
    'Hathor',
    'Anhur',
    'Khnum',
    'Wadjet',
    'Sobek',
    'Bast',
    'Anuket',
  ],
};

const t_polynesian_mythology: Theme = {
  identifier: 'polynesian-mythology',
  name: 'Polynesian Mythology',
  names: [
    'Maui',
    'Tane',
    'Pele',
    'Hina',
    'Kane',
    'Kanaloa',
    'Mahuika',
    'Whiro',
    'Tawhiri',
    'Rongo',
    'Tangaroa',
    'Haumia',
    'Papa',
    'Rangi',
  ],
};

const t_roman_mythology: Theme = {
  identifier: 'roman-mythology',
  name: 'Roman Mythology',
  names: [
    'Jupiter',
    'Juno',
    'Neptune',
    'Minerva',
    'Mars',
    'Venus',
    'Apollo',
    'Diana',
    'Mercury',
    'Vulcan',
    'Ceres',
    'Bacchus',
    'Proserpina',
    'Pluto',
    'Vesta',
    'Aeneas',
    'Remus',
    'Romulus',
    'Cupid',
    'Faunus',
    'Janus',
    'Juturna',
    'Latona',
    'Lucina',
    'Quirinus',
    'Saturn',
    'Silvanus',
    'Terminus',
    'Ops',
    'Flora',
    'Pomona',
    'Fides',
    'Lares',
    'Manes',
    'Genius',
    'Nona',
    'Decima',
    'Morta',
    'Carmenta',
    'Egeria',
    'Pales',
    'Pax',
    'Victoria',
    'Bellona',
    'Concordia',
    'Liber',
    'Salus',
  ],
};

const c_mythology: Category = {
  name: 'Mythology ⚡',
  language: 'EN',
  bgColor: '#FFC83D',
  themes: [
    t_norse_mythology,
    t_greek_mythology,
    t_egyptian_mythology,
    t_polynesian_mythology,
    t_roman_mythology,
  ],
};

//////////////////////////////////////////////
///////       Locations Category     /////////
//////////////////////////////////////////////

const t_countries: Theme = {
  identifier: 'countries',
  name: 'Countries',
  names: [
    'Japan',
    'Brazil',
    'Canada',
    'Mexico',
    'France',
    'Germany',
    'Italy',
    'Spain',
    'China',
    'India',
    'Russia',
    'Egypt',
    'Greece',
    'Turkey',
    'Norway',
    'Sweden',
    'Denmark',
    'Finland',
    'Iceland',
    'Ireland',
    'Poland',
    'Portugal',
    'Belgium',
    'Austria',
    'Argentina',
    'Chile',
    'Peru',
    'Colombia',
    'Australia',
    'New Zealand',
    'South Korea',
    'Vietnam',
    'Thailand',
    'Indonesia',
    'Malaysia',
    'Singapore',
    'Pakistan',
    'Iran',
    'Iraq',
    'Israel',
    'Jordan',
    'Lebanon',
    'Syria',
    'Kuwait',
    'Qatar',
  ],
};

const t_us_states: Theme = {
  identifier: 'us-states',
  name: 'U.S States',
  names: [
    'California',
    'Texas',
    'Florida',
    'New York',
    'Ohio',
    'Georgia',
    'Michigan',
    'Virginia',
    'Arizona',
    'Tennessee',
    'Indiana',
    'Missouri',
    'Maryland',
    'Wisconsin',
    'Colorado',
    'Minnesota',
    'Alabama',
    'Louisiana',
    'Kentucky',
    'Oregon',
    'Oklahoma',
    'Iowa',
    'Arkansas',
    'Utah',
    'Nevada',
    'Kansas',
    'Nebraska',
    'Idaho',
    'Hawaii',
    'Maine',
    'Montana',
    'Delaware',
    'Vermont',
  ],
};

const t_islands: Theme = {
  identifier: 'islands',
  name: 'Islands',
  names: [
    'Bahamas',
    'Fiji',
    'Hawaii',
    'Jamaica',
    'Bali',
    'Maldives',
    'Samoa',
    'Borneo',
    'Tahiti',
    'Cuba',
    'Santorini',
    'Corsica',
    'Sicily',
    'Ibiza',
    'Crete',
    'Malta',
    'Cyprus',
    'Tonga',
    'Lombok',
    'Capri',
    'Rhodes',
    'Aruba',
    'Montserrat',
    'Antigua',
    'Curacao',
    'Martinique',
    'Guadeloupe',
    'Mallorca',
    'Ibiza',
    'Dominica',
    'Grenada',
  ],
};

const t_biomes: Theme = {
  identifier: 'biomes',
  name: 'Biomes',
  names: [
    'Tundra',
    'Ocean',
    'Savannah',
    'Desert',
    'Grassland',
    'Taiga',
    'Rainforest',
    'Marsh',
    'Swamp',
    'Mountain',
    'Forest',
    'Jungle',
    'Steppe',
    'Prairie',
    'Plateau',
    'Canyon',
    'Delta',
    'Mangrove',
    'Lagoon',
    'Fjord',
    'Estuary',
    'Coral Reef',
    'Volcano',
    'Glacier',
    'Atoll',
    'Cave',
    'Oasis',
    'Dune',
    'Cliff',
    'Bayou',
    'Pond',
    'Lake',
    'River',
    'Waterfall',
    'Bluff',
    'Fen',
    'Bog',
    'Moor',
    'Badlands',
    'Crag',
    'Gorge',
    'Hill',
    'Plain',
    'Peninsula',
    'Cove',
    'Channel',
    'Sinkhole',
    'Butte',
  ],
};

const t_cities: Theme = {
  identifier: 'cities',
  name: 'Cities',
  names: [
    'Tokyo',
    'Paris',
    'London',
    'Sydney',
    'Moscow',
    'Berlin',
    'Rome',
    'Dubai',
    'Bangkok',
    'Toronto',
    'Madrid',
    'Seoul',
    'Mumbai',
    'Cairo',
    'Venice',
    'Athens',
    'Lisbon',
    'Prague',
    'Vienna',
    'Amsterdam',
    'Hanoi',
    'Jakarta',
    'Chicago',
    'Shanghai',
    'Beijing',
    'Singapore',
    'Dublin',
    'Lagos',
    'Milan',
    'Lima',
    'Kiev',
    'New York',
    'Los Angeles',
    'San Diego',
    'Boston',
    'Miami',
    'Houston',
    'Dallas',
    'Seattle',
    'Denver',
    'Phoenix',
    'Atlanta',
    'Detroit',
    'Manchester',
    'Liverpool',
    'Bristol',
    'Leeds',
    'York',
    'Oxford',
    'Cambridge',
  ],
};

const t_astrology: Theme = {
  identifier: 'astrology',
  name: 'Astrology',
  names: [
    'Aries',
    'Taurus',
    'Gemini',
    'Cancer',
    'Leo',
    'Virgo',
    'Libra',
    'Scorpio',
    'Capricorn',
    'Aquarius',
    'Pisces',
    'Sun',
    'Moon',
    'Mercury',
    'Venus',
    'Mars',
    'Jupiter',
    'Saturn',
    'Uranus',
    'Neptune',
    'Pluto',
    'Elements',
    'Fire',
    'Earth',
    'Air',
    'Water',
    'Qualities',
    'Cardinal',
    'Fixed',
    'Mutable',
    'Houses',
    'First',
    'Second',
    'Third',
    'Fourth',
    'Fifth',
    'Sixth',
    'Seventh',
    'Eighth',
    'Ninth',
    'Tenth',
    'Eleventh',
    'Twelfth',
    'Aspects',
    'Trine',
    'Square',
    'Opposition',
  ],
};

const c_locations: Category = {
  name: 'Locations 🌋',
  language: 'EN',
  bgColor: '#F7630C',
  themes: [t_countries, t_us_states, t_islands, t_biomes, t_cities, t_astrology],
};

//////////////////////////////////////////////
//////       Human Names Category     ////////
//////////////////////////////////////////////

const t_us_presidents: Theme = {
  identifier: 'us-presidents',
  name: 'U.S Presidents',
  names: [
    'Washington',
    'Adams',
    'Jefferson',
    'Madison',
    'Monroe',
    'Jackson',
    'Van Buren',
    'Harrison',
    'Tyler',
    'Polk',
    'Taylor',
    'Fillmore',
    'Pierce',
    'Buchanan',
    'Lincoln',
    'Grant',
    'Hayes',
    'Garfield',
    'Arthur',
    'Cleveland',
    'Harrison',
    'McKinley',
    'Roosevelt',
    'Taft',
    'Wilson',
    'Harding',
    'Coolidge',
    'Hoover',
    'Truman',
    'Eisenhower',
    'Kennedy',
    'Johnson',
    'Nixon',
    'Ford',
    'Carter',
    'Reagan',
    'Clinton',
    'Bush',
    'Obama',
    'Trump',
    'Biden',
  ],
};

const t_celebrities: Theme = {
  identifier: 'celebrities',
  name: 'Celebrities',
  names: [
    'Elvis',
    'Beyoncé',
    'Madonna',
    'Prince',
    'Cher',
    'Adele',
    'Drake',
    'Ariana',
    'Taylor',
    'Eminem',
    'Rihanna',
    'Shakira',
    'Monroe',
    'Streep',
    'Cruise',
    'Clooney',
    'Denzel',
    'Pitt',
    'Jolie',
    'Depp',
    'Lawrence',
    'DiCaprio',
    'Gaga',
    'Swift',
    'Kanye',
    'Lopez',
    'Bieber',
    'Stallone',
    'Hanks',
    'Perry',
    'Cyrus',
    'Lana',
    'Jolie',
    'Hathaway',
    'Damon',
    'Johansson',
    'Bale',
    'Diaz',
    'Hathaway',
    'Gosling',
    'Phoenix',
    'Kutcher',
    'Kidman',
    'Cavill',
    'Jackman',
    'Fox',
    'Gosling',
  ],
};

const t_historic_figures: Theme = {
  identifier: 'historic-figures',
  name: 'Historic Figures',
  names: [
    'Newton',
    'Galileo',
    'Einstein',
    'Da Vinci',
    'Cleopatra',
    'Napoleon',
    'Gandhi',
    'Lincoln',
    'Churchill',
    'Mozart',
    'Tesla',
    'Columbus',
    'Marie Curie',
    'Socrates',
    'Nelson',
    'Confucius',
    'Plato',
    'Aristotle',
    'Bach',
    'Catherine',
    'Hemingway',
    'Tolkien',
    'Genghis',
    'Voltaire',
    'Washington',
    'Darwin',
    'Alexander',
    'Spartacus',
    'Copernicus',
    'Freud',
    'Rembrandt',
    'Beethoven',
    'Cicero',
    'Marx',
    'Nero',
    'Homer',
    'Pablo',
    'Remus',
    'Pocahontas',
    'Joan of Arc',
    'Attila',
    'Houdini',
    'Euler',
    'Houdini',
  ],
};

const t_athletes: Theme = {
  identifier: 'athletes',
  name: 'Athletes',
  names: [
    'Jordan',
    'Ali',
    'Serena',
    'Federer',
    'Ronaldo',
    'Messi',
    'Tiger Woods',
    'Nadal',
    'Bolt',
    'Pele',
    'Neymar',
    'Beckham',
    'Mia Hamm',
    'Biles',
    'Frazier',
    'Nadia',
    'Rousey',
    'Phelps',
    'Gretzky',
    'Maradona',
    'Senna',
    'Sharapova',
    'Federer',
    'Ginobili',
    'Kobe',
    'Bolt',
    'Nadal',
    'Ali',
    'Brady',
    'Gehrig',
    'Marino',
    'Shaq',
    'Woods',
    'Zidane',
    'Djokovic',
    'Nash',
    'Pele',
    'Cristiano',
    'Magic',
    'Wade',
    'Graf',
    'Rodman',
    'Messi',
    'Curry',
    'Durant',
    'Murray',
  ],
};

const c_human_names: Category = {
  name: 'Human Names 🙋‍♂️',
  language: 'EN',
  bgColor: '#3A96DD',
  themes: [t_us_presidents, t_celebrities, t_historic_figures, t_athletes],
};

//////////////////////////////////////////////
/////////       Sports Category     //////////
//////////////////////////////////////////////

const t_sports: Theme = {
  name: 'Sports',
  identifier: 'sports',
  names: [
    'Soccer',
    'Football',
    'Baseball',
    'Basketball',
    'Hockey',
    'Tennis',
    'Golf',
    'Boxing',
    'Cricket',
    'Rugby',
    'Wrestling',
    'Skating',
    'Cycling',
    'Skiing',
    'Surfing',
    'Rowing',
    'Archery',
    'Fencing',
    'Diving',
    'Bowling',
    'Curling',
    'Judo',
    'Karate',
    'Lacrosse',
    'Softball',
    'Volleyball',
    'Badminton',
    'Gymnastics',
    'Handball',
    'Equestrian',
  ],
};

const t_sports_equipment: Theme = {
  name: 'Sports Equipment',
  identifier: 'sports-equipment',
  names: [
    'Ball',
    'Bat',
    'Racket',
    'Glove',
    'Helmet',
    'Net',
    'Puck',
    'Pad',
    'Stick',
    'Goal',
    'Shoes',
    'Cleats',
    'Goggles',
    'Jersey',
    'Mat',
    'Skates',
    'Board',
    'Saddle',
    'Rope',
    'Bar',
    'Bike',
    'Dumbbell',
    'Disc',
    'Paddle',
    'Flippers',
    'Club',
    'Hoop',
    'Tee',
    'Wickets',
    'Harness',
    'Shuttle',
    'Anchor',
    'SwimCap',
    'Whistle',
    'KneePads',
    'Headband',
    'TennisSho',
    'Basket',
    'Armguard',
    'Mouthguard',
    'PunchBag',
    'YogaMat',
    'WaterBott',
    'Javelin',
    'Hammer',
    'Dartboard',
    'BocceBall',
    'SurfBoard',
    'SkiPoles',
  ],
};

const t_nfl_teams: Theme = {
  name: 'NFL Teams',
  identifier: 'nfl-teams',
  names: [
    'Cardinals',
    'Falcons',
    'Ravens',
    'Bills',
    'Panthers',
    'Bears',
    'Bengals',
    'Browns',
    'Cowboys',
    'Broncos',
    'Lions',
    'Packers',
    'Texans',
    'Colts',
    'Jaguars',
    'Chiefs',
    'Raiders',
    'Chargers',
    'Rams',
    'Dolphins',
    'Vikings',
    'Patriots',
    'Saints',
    'Giants',
    'Jets',
    'Eagles',
    'Steelers',
    '49ers',
    'Seahawks',
    'Buccaneers',
    'Titans',
    'Commanders',
  ],
};

const t_nba_teams: Theme = {
  name: 'NBA Teams',
  identifier: 'nba-teams',
  names: [
    'Hawks',
    'Celtics',
    'Nets',
    'Hornets',
    'Bulls',
    'Cavaliers',
    'Mavericks',
    'Nuggets',
    'Pistons',
    'Warriors',
    'Rockets',
    'Pacers',
    'Clippers',
    'Lakers',
    'Grizzlies',
    'Heat',
    'Bucks',
    'Pelicans',
    'Knicks',
    'Thunder',
    'Magic',
    '76ers',
    'Suns',
    'Kings',
    'Spurs',
    'Raptors',
    'Jazz',
    'Wizards',
  ],
};

const t_nhl_teams: Theme = {
  name: 'NHL Teams',
  identifier: 'nhl-teams',
  names: [
    'Ducks',
    'Coyotes',
    'Bruins',
    'Sabres',
    'Flames',
    'Hurricanes',
    'Blackhawks',
    'Avalanche',
    'Blue Jacket',
    'Stars',
    'Red Wings',
    'Oilers',
    'Panthers',
    'Kings',
    'Wild',
    'Canadiens',
    'Predators',
    'Devils',
    'Islanders',
    'Rangers',
    'Senators',
    'Flyers',
    'Penguins',
    'Sharks',
    'Kraken',
    'Blues',
    'Lightning',
    'Maple Leafs',
    'Canucks',
    'Capitals',
    'Jets',
  ],
};

const t_mlb_teams: Theme = {
  name: 'MLB Teams',
  identifier: 'mlb-teams',
  names: [
    'Braves',
    'Orioles',
    'Red Sox',
    'Cubs',
    'White Sox',
    'Reds',
    'Guardians',
    'Rockies',
    'Tigers',
    'Astros',
    'Royals',
    'Angels',
    'Dodgers',
    'Marlins',
    'Brewers',
    'Twins',
    'Mets',
    'Yankees',
    'Athletics',
    'Phillies',
    'Pirates',
    'Padres',
    'Giants',
    'Mariners',
    'Cardinals',
    'Rays',
    'Rangers',
    'Blue Jays',
    'Nationals',
  ],
};

const t_premier_league_teams: Theme = {
  name: 'Premiere League Teams',
  identifier: 'premiere-league-teams',
  names: [
    'Arsenal',
    'Aston Villa',
    'Brentford',
    'Brighton',
    'Burnley',
    'Chelsea',
    'Everton',
    'Fulham',
    'Liverpool',
    'Luton Town',
    'Man City',
    'Man United',
    'Newcastle',
    'Sheffield',
    'Tottenham',
    'West Ham',
    'Wanderers',
  ],
};

const t_wnba_teams: Theme = {
  name: 'WNBA Teams',
  identifier: 'wnba-teams',
  names: [
    'Dream',
    'Sky',
    'Sun',
    'Wings',
    'Fever',
    'Aces',
    'Sparks',
    'Lynx',
    'Liberty',
    'Mercury',
    'Storm',
    'Mystics',
  ],
};

const c_sports: Category = {
  name: 'Sports 🏈',
  language: 'EN',
  bgColor: '#8E562E',
  themes: [
    t_sports,
    t_sports_equipment,
    t_nfl_teams,
    t_nba_teams,
    t_nhl_teams,
    t_mlb_teams,
    t_premier_league_teams,
    t_wnba_teams,
  ],
};

//////////////////////////////////////////////
/////////       Items Category     ///////////
//////////////////////////////////////////////

const t_tools: Theme = {
  name: 'Tools',
  identifier: 'tools',
  names: [
    'Hammer',
    'Wrench',
    'Screwdrivr',
    'Pliers',
    'Chisel',
    'Saw',
    'Drill',
    'Level',
    'Knife',
    'Ruler',
    'File',
    'Awl',
    'Punch',
    'Vise',
    'Tongs',
    'Brush',
    'Tape',
    'Scissors',
    'Anvil',
    'Clamp',
    'Chainsaw',
    'Sander',
    'Auger',
    'Trowel',
    'Router',
    'Planes',
    'Jack',
    'Gimlet',
    'Rasps',
    'Mallet',
    'Torch',
    'Shears',
    'Spade',
    'Pincer',
    'Ladle',
    'Peg',
    'Jigsaw',
    'Tweezers',
    'Rivet',
    'Pickle',
  ],
};

const t_household_items: Theme = {
  name: 'Household Items',
  identifier: 'household-items',
  names: [
    'Chair',
    'Table',
    'Couch',
    'Lamp',
    'Mirror',
    'Plate',
    'Glass',
    'Fork',
    'Knife',
    'Spoon',
    'Pot',
    'Pan',
    'Sheet',
    'Pillow',
    'Blanket',
    'Towel',
    'Soap',
    'Brush',
    'Clock',
    'Radio',
    'Phone',
    'Remote',
    'Broom',
    'Mop',
    'Duster',
    'Rug',
    'Mat',
    'Basket',
    'Bucket',
    'Tray',
    'Drawer',
    'Shelf',
    'Hanger',
    'Hook',
    'Knife',
    'Grater',
    'Whisk',
    'Mixer',
    'Oven',
    'Fridge',
    'Freezer',
    'Toaster',
    'Kettle',
    'Potato',
    'Cereal',
    'Juicer',
    'Blender',
  ],
};

const t_tech_devices: Theme = {
  name: 'Tech Devices',
  identifier: 'tech-devices',
  names: [
    'Phone',
    'Tablet',
    'Laptop',
    'Desktop',
    'Mouse',
    'Keyboard',
    'Monitor',
    'Printer',
    'Router',
    'Modem',
    'Scanner',
    'Speaker',
    'Headphones',
    'Earbuds',
    'Camera',
    'Drone',
    'Smartwatch',
    'Fitbit',
    'Charger',
    'Router',
    'Hub',
    'Cable',
    'Adapter',
    'Projector',
    'Console',
    'Xbox',
    'PlayStation',
    'Switch',
    'TV',
    'SmartTV',
    'Remote',
    'Speaker',
    'Subwoofer',
    'Microphone',
    'Webcam',
    'GPS',
    'Drive',
    'SSD',
  ],
};

const t_minerals: Theme = {
  name: 'Minerals',
  identifier: 'minerals',
  names: [
    'Quartz',
    'Calcite',
    'Feldspar',
    'Gypsum',
    'Topaz',
    'Corundum',
    'Halite',
    'Pyrite',
    'Beryl',
    'Hematite',
    'Galena',
    'Fluorite',
    'Magnetite',
    'Apatite',
    'Talc',
    'Garnet',
    'Opal',
    'Amber',
    'Jadeite',
    'Agate',
    'Malachite',
    'Lapis',
    'Onyx',
    'Obsidian',
    'Peridot',
    'Sapphire',
    'Jasper',
    'Tourmaline',
    'Turquoise',
    'Zircon',
    'Citrine',
    'Emerald',
    'Azurite',
    'Olivine',
    'Gold',
    'Silver',
    'Platinum',
    'Diamond',
    'Ruby',
    'Copper',
    'Nickel',
    'Tin',
    'Lead',
    'Zinc',
    'Iron',
    'Titanium',
    'Mica',
    'Coal',
  ],
};

const t_clothes: Theme = {
  name: 'Clothes',
  identifier: 'clothes',
  names: [
    'Shirt',
    'Pants',
    'Dress',
    'Skirt',
    'Shorts',
    'Jeans',
    'Socks',
    'Shoes',
    'Boots',
    'Gloves',
    'Coat',
    'Jacket',
    'Scarf',
    'Hat',
    'Cap',
    'Hoodie',
    'Sweater',
    'Blouse',
    'Tank Top',
    'Vest',
    'Tie',
    'Belt',
    'Suit',
    'Blazer',
    'Pajamas',
    'Robe',
    'Slippers',
    'Sandals',
    'Leggings',
    'Tights',
    'Bras',
    'Underwear',
    'Swimsuit',
    'Raincoat',
    'Parka',
    'Gown',
    'Cardigan',
    'Jumpsuit',
    'Tuxedo',
    'Poncho',
    'Cape',
    'Apron',
    'Turtleneck',
    'Kilt',
    'Bandana',
    'Mittens',
    'Beanie',
  ],
};

const t_elements: Theme = {
  name: 'Elements',
  identifier: 'elements',
  names: [
    'Hydrogen',
    'Helium',
    'Lithium',
    'Beryllium',
    'Boron',
    'Carbon',
    'Nitrogen',
    'Oxygen',
    'Fluorine',
    'Neon',
    'Sodium',
    'Magnesium',
    'Aluminum',
    'Silicon',
    'Phosphorus',
    'Sulfur',
    'Chlorine',
    'Argon',
    'Potassium',
    'Calcium',
    'Scandium',
    'Titanium',
    'Vanadium',
    'Chromium',
    'Manganese',
    'Iron',
    'Cobalt',
    'Nickel',
    'Copper',
    'Zinc',
    'Gallium',
    'Germanium',
    'Arsenic',
    'Selenium',
    'Bromine',
    'Krypton',
    'Rubidium',
    'Strontium',
    'Yttrium',
    'Zirconium',
    'Niobium',
    'Molybdenum',
    'Technetium',
    'Ruthenium',
    'Rhodium',
    'Palladium',
    'Silver',
    'Cadmium',
  ],
};

const c_items: Category = {
  name: 'Items 💎',
  language: 'EN',
  bgColor: '#31D2F7',
  themes: [t_tools, t_household_items, t_tech_devices, t_minerals, t_clothes, t_elements],
};

//////////////////////////////////////////////
/////////       Movies Category     //////////
//////////////////////////////////////////////

const t_movies: Theme = {
  name: 'Movies',
  identifier: 'movies',
  names: [
    'Alien',
    'Titanic',
    'Jaws',
    'Psycho',
    'Rocky',
    'Gravity',
    'Avatar',
    'Memento',
    'Speed',
    'Casino',
    'Taken',
    'Glitter',
    'Crank',
    'Twins',
    'Scream',
    'Heat',
    'Scarface',
    'Jumper',
    'Closer',
    'Skyfall',
    'Whiplash',
    'Airplane',
    'Superbad',
    'Kick-Ass',
    'Panic',
    'Blade',
    'Sicario',
    'Misery',
    'Saw',
    'Looper',
    'Zorro',
    'Fury',
    'Push',
    'Cargo',
    'Pulse',
    'Chaos',
    'Bliss',
    'Rush',
    'Joker',
    'Seven',
    'Fargo',
    'Horns',
    'Clown',
    'Break',
    'Venom',
    'Glory',
    'Ghost',
    'Pi',
    'Vice',
  ],
};

const t_movie_characters: Theme = {
  name: 'Movie Characters',
  identifier: 'movie-characters',
  names: [
    'Neo',
    'Han Solo',
    'Luke',
    'Leia',
    'Trinity',
    'Morpheus',
    'Frodo',
    'Gandalf',
    'Sam',
    'Bilbo',
    'Legolas',
    'Aragorn',
    'Gollum',
    'Darth Vader',
    'Yoda',
    'Obi-Wan',
    'Padmé',
    'Anakin',
    'Han Solo',
    'Chewbacca',
    'R2-D2',
    'C-3PO',
    'Rey',
    'Kylo Ren',
    'Finn',
    'Marty',
    'Doc',
    'Doc Brown',
    'E.T.',
    'Elliot',
    'Indiana',
    'Marion',
    'Hannibal',
    'Clarice',
    'Jack',
    'Rose',
    'Joker',
    'Batman',
    'Robin',
    'Catwoman',
    'Superman',
    'Spider-Man',
    'Iron Man',
    'Captain',
    'Black Widow',
    'Thor',
    'Hulk',
    'Wolverine',
    'Logan',
    'Storm',
    'Magneto',
    'Professor',
    'Ripley',
    'Hicks',
    'Newt',
    'T-800',
    'Sarah',
    'John',
    'Terminator',
    'Ripley',
    'Hicks',
    'Newt',
    'T-800',
    'Sarah',
    'John',
    'Terminator',
    'John Connor',
    'Travis',
    'Bickle',
    'Jake',
    'LaMotta',
    'Pacino',
    'Michael',
    'Vito',
    'Corleone',
    'Tony',
    'Montana',
    'Sullivan',
    'Elsa',
    'Rick',
    'Ilsa',
    'Sam',
    'Holly',
    'Paul',
    'Patton',
    'Barney',
    'Mickey',
  ],
};

const t_disney_movies: Theme = {
  name: 'Disney Movies',
  identifier: 'disney-movies',
  names: [
    'Frozen',
    'Aladdin',
    'Mulan',
    'Coco',
    'Tangled',
    'Zootopia',
    'Moana',
    'Brave',
    'Fantasia',
    'Cinderella',
    'Dumbo',
    'Bambi',
    'Tarzan',
    'Frozen II',
    'Incredibles',
    'Pocahontas',
    'Peter Pan',
    'Jungle Book',
    'Pinocchio',
    'Lion King',
    'Big Hero 6',
    'WALL-E',
    'Inside Out',
  ],
};

const t_disney_characters: Theme = {
  name: 'Disney Characters',
  identifier: 'disney-characters',
  names: [
    'Mickey',
    'Minnie',
    'Donald',
    'Goofy',
    'Pluto',
    'Daisy',
    'Chip',
    'Dale',
    'Scrooge',
    'Huey',
    'Dewey',
    'Louie',
    'Maximus',
    'Simba',
    'Nala',
    'Timon',
    'Pumbaa',
    'Mufasa',
    'Baloo',
    'Bagheera',
    'Mowgli',
    'Ariel',
    'Flounder',
    'Sebastian',
    'Ursula',
    'Peter Pan',
    'Tinker Bell',
    'Wendy',
    'Captain Hook',
    'Cinderella',
    'Tiana',
    'Rapunzel',
    'Elsa',
    'Anna',
    'Olaf',
    'Belle',
    'Beast',
    'Aladdin',
    'Jasmine',
    'Genie',
    'Pocahontas',
    'Merida',
    'Aurora',
    'Mulan',
    'Hercules',
    'Megara',
    'Tarzan',
    'Jane',
    'Winnie',
    'Pooh',
    'Tigger',
    'Piglet',
    'Eeyore',
    'Roo',
    'Kanga',
    'Lilo',
    'Stitch',
    'Judy',
    'Nick',
    'Elsa',
    'Anna',
    'Kristoff',
    'Sven',
    'Baymax',
    'Hiro',
    'Remy',
    'Wall-E',
    'Mike',
    'Sully',
    'Boo',
    'Woody',
    'Buzz',
    'Jessie',
    'Frozone',
    'Dash',
    'Violet',
    'Edna',
    'Merlin',
    'Dumbo',
    'Bambi',
    'Pinocchio',
    'Jiminy',
    'Aristocats',
    'Robin Hood',
    'Duchess',
    'Thomas',
    'Marie',
    'Berlioz',
    'Duchess',
    'Bagheera',
    'Kaa',
    'Tiana',
    'Pascal',
    'Maximus',
    'Fairy',
    'Flora',
    'Fauna',
  ],
};

const t_actors: Theme = {
  name: 'Actors',
  identifier: 'actors',
  names: [
    'Tom Hanks',
    'Brad Pitt',
    'Matt Damon',
    'Tom Cruise',
    'Will Smith',
    'Downey Jr',
    'Hugh',
    'Wahlberg',
    'Leonardo',
    'Depp',
    'Denzel',
    'Meryl',
    'Roberts',
    'Scarlett',
    'Stone',
    'Sandra',
    'Angelina',
    'Natalie',
    'Hathaway',
    'Blanchett',
    'Kidman',
    'Jessica',
    'Charlize',
    'Blunt',
    'Winslet',
    'Halle',
    'Viola',
    'Rachel',
    'Amy Adams',
    'Gwyneth',
    'Reese',
    'Hudson',
    'Diaz',
    'Keira',
    'Jodie',
    'Helena',
    'Michelle',
    'Wilde',
    'Mila Kunis',
    'Zoe Saldana',
    'Penelope',
    'Salma',
    'Eva Mendes',
    'Lucy Liu',
    'Diane Lane',
    'Zellweger',
    'Duff',
    'Fanning',
    'Maggie',
    'Liv Tyler',
    'Eva Green',
    'Blake',
    'Megan Fox',
    'Evan Rachel',
    'Zooey',
    'Kendrick',
    'Shailene',
    'Swank',
    'Judi Dench',
    'Knightley',
    'Winona',
    'Jennifer',
    'Greta',
    'Alicia',
    'Rosamund',
    'Gal Gadot',
    'Octavia',
    'Melissa',
    'Emma',
    'Saoirse',
    'Zendaya',
    'Brie',
    'Charlize',
    'Stewart',
    'Bynes',
    'Mary',
  ],
};

const c_movies: Category = {
  name: 'Movies 🎬',
  language: 'EN',
  bgColor: '#383838',
  themes: [t_movies, t_movie_characters, t_disney_movies, t_disney_characters, t_actors],
};

//////////////////////////////////////////////
///////       Video Games Category     ///////
//////////////////////////////////////////////

const t_games: Theme = {
  name: 'Games',
  identifier: 'games',
  names: [
    'Pac-Man',
    'Tetris',
    'Mario Kart',
    'Sonic',
    'Minecraft',
    'Overwatch',
    'Fortnite',
    'Pokémon',
    'Zelda',
    'Fallout',
    'Skyrim',
    'Portal',
    'Doom',
    'FIFA',
    'Splatoon',
    'Diablo',
    'Starcraft',
    'Warcraft',
    'Madden',
    '2k',
    'Destiny',
    'Halo',
    'Tekken',
    'Crash',
    'Kirby',
    'Bioshock',
    'Terraria',
    'Stardew',
    'Undertale',
    'Limbo',
    'Pong',
    'Celeste',
    'Hollow',
    'Inside',
    'Braid',
    'Thumper',
    'Apex Legend',
    'Returnal',
    'Cyberpunk',
    'Fall Guys',
    'Last of Us',
    'Dota 2',
    'Hitman',
    'Bloodborne',
    'Hades',
    'Control',
    'Among Us',
    'Cyberpunk',
    'FIFA 21',
    'God of War',
    'Fortnite',
    'Among Us',
    'Valorant',
    'Dead Cells',
    'Cuphead',
    "No Man's Sky",
  ],
};

const t_game_characters: Theme = {
  name: 'Game Characters',
  identifier: 'game-characters',
  names: [
    'Kratos',
    'Atreus',
    'Aloy',
    'Ellie',
    'Joel',
    'Nathan',
    'Senua',
    'Bayek',
    'Eivor',
    'Cassandra',
    'Alexios',
    'Geralt',
    'Yennefer',
    'Tracer',
    'Reinhardt',
    'Sombra',
    'Jesse',
    'Abby',
    'Aloy',
    'Rost',
    'Doomguy',
    'Jill',
    'Nemesis',
    'Eivor',
    'Kassandra',
    'Ryu',
    'Ken',
    'Chun-Li',
    'Cammy',
    'Link',
    'Zelda',
    'Ganondorf',
    'Marth',
    'Samus',
    'Fox',
    'Cortana',
    'Marcus',
    'Dom',
    'Lara',
    'Croft',
    'Kratos',
    'Aloy',
    'Senua',
    'Max',
    'Chloe',
    'Aloy',
    'Nathan',
    'Kratos',
    'Lara',
  ],
};

const t_minecraft: Theme = {
  name: 'Minecraft',
  identifier: 'minecraft',
  names: [
    'Steve',
    'Alex',
    'Creeper',
    'Enderman',
    'Zombie',
    'Skeleton',
    'Spider',
    'Cave',
    'Diamond',
    'Gold',
    'Iron',
    'Emerald',
    'Obsidian',
    'Lava',
    'Water',
    'Redstone',
    'Villager',
    'Ender',
    'Golem',
    'Pigman',
    'Blaze',
    'Ghast',
    'Slime',
    'Magma',
    'Guardian',
    'Shulker',
    'Witch',
    'Dragon',
    'Wither',
    'Nether',
    'Mineshaft',
    'Biome',
    'Portal',
    'Enchant',
    'Craft',
    'Block',
    'Pickaxe',
    'Sword',
    'Bow',
    'Arrow',
    'Helmet',
    'Armor',
    'Boots',
    'Shield',
    'Food',
    'Chest',
    'Bed',
    'Furnace',
    'Anvil',
    'Brew',
    'Map',
    'Compass',
    'Clock',
    'Bucket',
    'Shears',
    'Trident',
    'Totem',
    'Elytra',
    'Shovel',
    'Axe',
    'Hoe',
    'Fence',
    'Gate',
    'Carrot',
    'Potato',
    'Wheat',
    'Melon',
    'Pumpkin',
    'Apple',
    'Berry',
    'Beacon',
    'Netherite',
    'Emerald',
    'Obsidian',
    'Redstone',
    'Lapis',
    'Coal',
    'Quartz',
    'Gravel',
    'Sand',
    'Clay',
    'Brick',
    'Slab',
    'Stairs',
    'Torch',
    'Lantern',
    'Chest',
    'Door',
    'Banner',
    'Painting',
    'Book',
    'Sign',
    'Trapdoor',
  ],
};

const t_pokemon: Theme = {
  name: 'Pokemon',
  identifier: 'pokemon',
  names: [
    'Lava Cookie',
    'Janine',
    'Fallarbor',
    'Drake',
    'Max Revive',
    'Caitlin',
    'Kukui',
    'PP Up',
    'Hoenn',
    'Wallace',
    'Full Heal',
    'Twinleaf',
    'Rustboro',
    'HP Up',
    'Hearthome',
    'Iron',
    'Whitney',
    'Snowpoint',
    'Dewford',
    'Giovanni',
    'Fortree',
    'Galar',
    'Karen',
    'Persim Berry',
    'Nacrene',
    'Chuck',
    'Berry',
    'Alder',
    'Max Ether',
    'Sinnoh',
    'Blue',
    'Alola',
    'Lorelei',
    'Grimsley',
    'Pallet',
    'Pryce',
    'Johto',
    'Koga',
    'Eterna',
    'Gardenia',
    'Alder',
    'Steven',
    'Great Ball',
    'Aspear Berry',
    'Brock',
    'Max Repel',
    'Saffron',
    'Shoal Shell',
    'Kalos',
    'Carbos',
    'Veilstone',
    'HP Restore',
    'Nuvema',
    'Chesto Berry',
    'Bruno',
    'Sitrus Berry',
    'Bertha',
    'Celestic',
    'Aaron',
    'Viridian',
    'Littleroot',
    'Sidney',
    'Paralyze',
    'Mossdeep',
    'Misty',
    'Leon',
    'Solaceon',
    'LtSurge',
    'Steven',
    'Candice',
    'Oldale',
    'Star Piece',
    'Diantha',
    'Petalburg',
    'Agatha',
    'Marshal',
    'Canalave',
    'Ice Heal',
    'Erika',
    'Will',
    'Maylene',
    'Revive',
    'Sabrina',
    'Lance',
    'Master Ball',
    'Clair',
    'Casteliacone',
    'Byron',
    'Celadon',
    'Roark',
    'Striaton',
    'Morty',
    'Lance',
    'Fuchsia',
    'Olivine',
    'Unova',
    'Cheren',
    'Burn Heal',
    'Super Repel',
    'Rare Candy',
    'Sunyshore',
    'Big Pearl',
    'Ultra Ball',
    'Escape Rope',
    'Falkner',
    'Indigo',
    'Zinc',
    'Lum Berry',
    'Jasmine',
    'Cynthia',
    'Antidote',
    'Potion',
    'Iris',
    'Accumula',
    'Protein',
    'Bugsy',
    'Shoal Salt',
    'Blackthorn',
    'Poke Ball',
    'Mauville',
    'Pastoria',
    'Ether',
    'Rare Bone',
    'Fantina',
    'Mahogany',
    'Crasher',
    'Kanto',
    'Jubilife',
    'Lavender',
    'Oreburgh',
    'Leppa Berry',
    'Max Elixir',
    'Calcium',
    'Repel',
    'Rawst Berry',
    'Blaine',
    'Flint',
    'PP Max',
    'Lavaridge',
    'Pewter',
    'Twinleaf',
    'Old Gateau',
    'Lucian',
    'Sandgem',
    'Elixir',
    'Vermilion',
    'Ecruteak',
    'Shauntal',
    'Goldenrod',
    'Roxie',
    'Phoebe',
    'Cinnabar',
    'Stardust',
    'Volkner',
    'Glacia',
    'Oran Berry',
    'Iris',
    'Awakening',
    'Cerulean',
    'Slateport',
    'Pecha Berry',
    'Pearl',
  ],
};

const t_gta: Theme = {
  name: 'Grand Theft Auto',
  identifier: 'gta',
  names: [
    'Niko',
    'Trevor',
    'Kuruma',
    'Devin',
    'Gauntlet',
    'Entity',
    'Tracey',
    'Roman',
    'Johnny',
    'Asuka',
    'Sweet',
    'Liberty',
    'Banshee',
    'Ryder',
    'Molly',
    'Massacro',
    'Tony',
    'Maverick',
    'Phoenix',
    'Amanda',
    'Hydra',
    'Chop',
    'Schafter',
    'Franklin',
    'Lamar',
    'Zentorno',
    'Issi',
    'Reaper',
    'Carbon',
    'Coquette',
    'Comet',
    'Ray',
    'Brucie',
    'Claude',
    'Sultan',
    'Catalina',
    'Akula',
    'Big Smoke',
    'Vacca',
    'Buzzard',
    'Elegy',
    'Vice City',
    'Luis',
    'Sabre',
    'Cheetah',
    'Misty',
    'Los Santos',
    'Futo',
    'Tommy',
    'Bullet',
    'Turismo',
    'Michael',
    'Hakuchou',
    'CJ',
    'Oppressor',
    'Frank',
    'Packie',
    'Jimmy',
    'Blista',
    'Deluxo',
    'Phil',
    'San Andreas',
    'Rapid GT',
    'San Fierro',
    'Infernus',
    'Kenji',
    'Voltic',
    'Jester',
    'Adder',
    'Blaine',
    'Casco',
    'Feltzer',
  ],
};

const t_mario: Theme = {
  name: 'Mario',
  identifier: 'mario',
  names: [
    '1-Up',
    'Coinbox',
    'Toad',
    'Fireball',
    'Boo',
    'Star',
    'Koopa',
    'Mushroom',
    'P-Wing',
    'Shell',
    'Toadette',
    'Power-up',
    'Diddy Kong',
    'Boomerang',
    'Magikoopa',
    'Bowser',
    'Donkey Kong',
    'Dry Bones',
    'Pipe',
    'Pauline',
    'Birdo',
    'Kart',
    'Mario',
    'Coin',
    'Hammer',
    'Goomba',
    'Peach',
    'Yoshi',
    'Bowser Jr.',
    'Feather',
    'Daisy',
    'King Boo',
    'ChainChomp',
    'Lakitu',
    'Leaf',
    'Kamek',
    'Block',
    'Warp Pipe',
    'Rosalina',
    'Wario',
    'Shy Guy',
    'Cape',
    'Luigi',
    'Bob-omb',
    'Nabbit',
    'Waluigi',
    'Starman',
  ],
};
const t_overwatch: Theme = {
  name: 'Overwatch',
  identifier: 'overwatch',
  names: [
    'Tracer',
    'Reaper',
    'Widowmaker',
    'Pharah',
    'Mercy',
    'Hanzo',
    'Junkrat',
    'Mei',
    'Torbjorn',
    'D.Va',
    'Reinhardt',
    'Roadhog',
    'Winston',
    'Zarya',
    'Ana',
    'Lucio',
    'Symmetra',
    'Zenyatta',
    'Genji',
    'McCree',
    'Sombra',
    'Orisa',
    'Doomfist',
    'Moira',
    'Brigitte',
    'Ashe',
    'Baptiste',
    'Sigma',
    'Echo',
  ],
};

const t_smash: Theme = {
  name: 'Super Smash Bros',
  identifier: 'super-smash-bros',
  names: [
    'Mario',
    'Luigi',
    'Peach',
    'Bowser',
    'Yoshi',
    'Donkey Kong',
    'Link',
    'Zelda',
    'Samus',
    'Kirby',
    'Fox',
    'Pikachu',
    'Jigglypuff',
    'Ness',
    'Marth',
    'Pit',
    'Meta Knight',
    'Wario',
    'Snake',
    'Sonic',
    'Mega Man',
    'Villager',
    'Little Mac',
    'Rosalina',
    'Bowser Jr.',
    'Inkling',
    'Isabelle',
  ],
};

const t_cod: Theme = {
  name: 'Call of Duty',
  identifier: 'call-of-duty',
  names: [
    'M14',
    'ACR',
    'Killhouse',
    'RPD',
    'SCAR',
    'Nuketown',
    'Favela',
    'M249',
    'Backlot',
    'Thompson',
    'P90',
    'Dome',
    'Crash',
    'Rust',
    'Vacant',
    'Hijacked',
    'M4 Carbine',
    'Bloc',
    'R700',
    'Galil',
    'Shipment',
    'MSR',
    'AUG',
    'UMP',
    'KSG',
    'Strike',
    'Chinatown',
    'MP5',
    'Derailed',
    'Pipeline',
    'FAMAS',
    'Terminal',
    'Showdown',
    'G36',
    'Model 1887',
    'UMP45',
    'M16',
    'Castle',
    'Highrise',
    'Overgrown',
    'Downpour',
    'TAR-21',
    'Bog',
    'Ambush',
    'Broadcast',
    'Vector',
    'Dragunov',
    'L86 LSW',
    'SPAS-12',
    'FNFAL',
    'Carentan',
    'Summit',
    'AK-47',
    'Crossfire',
    'Countdown',
    'Barrett',
  ],
};
const t_stardew: Theme = {
  name: 'Stardew Valley',
  identifier: 'stardew-valley',
  names: [
    'Krobus',
    'Emily',
    'Penny',
    'Jodi',
    'Demetrius',
    'Willy',
    'Haley',
    'Sebastian',
    'Elliott',
    'George',
    'Clint',
    'Vincent',
    'Leah',
    'Marnie',
    'Caroline',
    'Robin',
    'Harvey',
    'Abigail',
    'Pam',
    'Kent',
    'Jas',
    'Sam',
    'Lewis',
    'Alex',
    'Pierre',
    'Linus',
    'Maru',
    'Gus',
    'Shane',
    'Evelyn',
  ],
};

const t_twd: Theme = {
  name: 'The Walking Dead',
  identifier: 'twd',
  names: [
    'Omid',
    'Jane',
    'Doug',
    'Negan',
    'Molly',
    'AJ',
    'Conrad',
    'Christa',
    'Luke',
    'Kate',
    'Mark',
    'Larry',
    'Sarah',
    'Tripp',
    'Lee',
    'Rebecca',
    'Rosita',
    'Lilly',
    'Gabe',
    'Michonne',
    'Ben',
    'Carley',
    'Kenny',
    'Alvin',
    'Clementine',
    'Javier',
    'Jesus',
    'Ezekiel',
    'Eleanor',
    'Maggie',
  ],
};

const t_monster_hunter: Theme = {
  name: 'Monster Hunter',
  identifier: 'monster-hunter',
  names: [
    'Deviljho',
    'Zinogre',
    'Nargacuga',
    'Odogaron',
    'Mizutsune',
    'Anjanath',
    'Khezu',
    'Rathian',
    'Rathalos',
    'Gammoth',
    'Astalos',
    'Kirin',
    'Teostra',
    'Velkhana',
    'Tigrex',
    'Kushala',
    'Nergigante',
    'Diablos',
    'Brachydios',
    'Yian Kut-Ku',
    'Barroth',
    'Gore Magala',
    'Rajang',
    'Lagiacrus',
    'Legiana',
    'Glavenus',
  ],
};

const t_witcher: Theme = {
  name: 'Witcher',
  identifier: 'witcher',
  names: [
    'Roche',
    'Vernon',
    'Cockatrice',
    'Griffin',
    'Cahir',
    'Ogre',
    'Vesemir',
    'Shani',
    'Gargoyle',
    'Leshen',
    'Zoltan',
    'Eskel',
    'Geralt',
    'Regis',
    'Wyvern',
    'Radovid',
    'Ekhidna',
    'Gaunter',
    'Alghoul',
    'Fiend',
    'Emhyr',
    'Dandelion',
    'Wraith',
    'Siren',
    'Barghest',
    'Arachas',
    "Avallac'h",
    'Yennefer',
    'Triss',
    'Nekker',
    'Keira',
    'Succubus',
    'Foglet',
    'Bruxa',
    'Lambert',
    'Iorveth',
    'Ciri',
    'Basilisk',
    'Drowner',
    'Werewolf',
  ],
};

const t_borderlands: Theme = {
  name: 'Borderlands',
  identifier: 'borderlands',
  names: [
    'Bee',
    'Dahl',
    'Flakker',
    'Nisha',
    'Hunter',
    'Claptrap',
    'Amara',
    'Bandit',
    'Lilith',
    'FL4K',
    'Hellfire',
    'Roland',
    'Maggie',
    'Commando',
    'Moze',
    'Butcher',
    'Wilhelm',
    'Sham',
    'Athena',
    'Tediore',
    'Pimpernel',
    'Lyuda',
    'Assassin',
    'Hornet',
    'Gunzerker',
    'Jack',
    'Hyperion',
    'Psycho',
    'Soldier',
    'Norfleet',
    'Zer0',
    'Maya',
    'Grog Nozzle',
    'Vladof',
    'Fastball',
    'Fiona',
    'Quasar',
    'Jakobs',
    'Siren',
    'Krieg',
    'Gaige',
    'Anshin',
    'Brick',
    'Berserker',
    'Atlas',
    'Axton',
    'Maliwan',
    'Torgue',
    'Sand Hawk',
    'Infinity',
    'Mordecai',
    'Salvador',
    'Rhys',
  ],
};

const t_content_creators: Theme = {
  name: 'Content Creators',
  identifier: 'content-creators',
  names: [
    'Valkyrae',
    'TommyInnit',
    'Vanoss',
    'Mini Ladd',
    'Corpse',
    'Sykkuno',
    'Nikkie',
    'Nadeshot',
    'Pokimane',
    'Ali-A',
    'Grian',
    'Markiplier',
    'MrBeast',
    'Jahova',
    'Poki',
    'Mumbo',
    'Felix',
    'Dream',
    'Ninja',
    'LazarBeam',
    'Courage',
    'Tfue',
    'DanTDM',
    'KSI',
    'Pokelawls',
    'PewDiePie',
    'Asmongold',
    'SSundee',
    'Shroud',
    'DrLupo',
    'Forsen',
    'Dantdm',
    'Ludwig',
    'Sodapoppin',
    'Amouranth',
    'Lachlan',
    'xQc',
    'Summit',
    'Jelly',
    'SypherPK',
    'Disguised',
  ],
};

const c_video_games: Category = {
  name: 'Video Games 🎮',
  language: 'EN',
  bgColor: '#757575',
  themes: [
    t_games,
    t_game_characters,
    t_minecraft,
    t_pokemon,
    t_content_creators,
    t_gta,
    t_mario,
    t_overwatch,
    t_smash,
    t_cod,
    t_stardew,
    t_twd,
    t_monster_hunter,
    t_witcher,
    t_borderlands,
  ],
};

//////////////////////////////////////////////
///////       Television Category     ////////
//////////////////////////////////////////////

const t_shows: Theme = {
  name: 'Shows',
  identifier: 'shows',
  names: [
    'Alias',
    'Arrow',
    'Tumble Leaf',
    'Oswald',
    'Gumby',
    'Lost',
    'ER',
    'Bubble',
    'Tinga',
    'Hey Duggee',
    'Octonauts',
    'MASH',
    'The Office',
    'Bluey',
    'Bob Builder',
    'Rugrats',
    'Pocoyo',
    'Castle',
    'My Little',
    'Vikings',
    'Cheers',
    'Rainbow',
    'Wiggles',
    'Odd Squad',
    'Wallykazam',
    'Masha',
    'Charlie',
    'Guppies',
    'Futurama',
    'Arthur',
    'Thomas',
    'Gotham',
    'Peppa Pig',
    'Kipper',
    'Bing',
    'Little Bear',
    'The Flash',
    'Heidi',
    'Psych',
    'Glee',
    'Berenstain',
    '24',
    'Firefly',
    'Suits',
    'House',
    'NCIS',
    'Curious',
    'DuckTales',
    'Family Guy',
    'Scrubs',
    'Noddy',
    'Daniel',
    'Chuck',
    'Furchester',
    'The Magic',
    'Friends',
    'Blippi',
    'Nella',
    'Mickey',
    'PJ Masks',
    'Paw Patrol',
    'SpongeBob',
    'Dinosaur',
    'Barney',
    'Dora',
    'Sherlock',
    'Bones',
    'Super Why',
    'Handy Manny',
    'Dexter',
    'Care Bears',
    'Clifford',
    'Frasier',
    'Seinfeld',
    'Buffy',
    'Heroes',
    'Daredevil',
  ],
};

const t_tv_characters: Theme = {
  name: 'TV Caracters',
  identifier: 'tv-character',
  names: [
    'Brian',
    'Stewie',
    'Boots',
    'Goku',
    'Peter',
    'Vegeta',
    'Sandy',
    'SpongeBob',
    'Maggie',
    'Chandler',
    'Tyrion',
    'Kyle',
    'Marge',
    'Rachel',
    'Stan',
    'Kenny',
    'Dexter',
    'Ted',
    'Squidward',
    'Joey',
    'Walter',
    'Dora',
    'Finn',
    'Scooby',
    'Barney',
    'Homer',
    'Jake',
    'Wolverine',
    'Lois',
    'Ross',
    'Robin',
    'Jon Snow',
    'Diego',
    'Sheldon',
    'Uniqua',
    'Pablo',
    'Monica',
    'Marshall',
    'Bart',
    'Phoebe',
    'Cartman',
    'Arya',
    'Meg',
    'Lisa',
    'Tasha',
    'Daenerys',
    'Lily',
    'Patrick',
    'Austin',
  ],
};

const t_cartoons: Theme = {
  name: 'Cartoons',
  identifier: 'cartoons',
  names: [
    'Phantom',
    'Ben 10',
    'Cunningham',
    'Beavis',
    'Steven',
    'Test',
    'Xiaolin',
    'Bears',
    'Butt-Head',
    'Danny',
    'Avatar',
    'Daria',
    'Adventure',
    'Go',
    'Futurama',
    'Showdown',
    'Ferb',
    'DuckTales',
    'BoJack',
    'Scooby-Doo',
    'Sonic',
    'South Park',
    'Gravity',
    'Max Steel',
    'Family Guy',
    'Johnny',
    'Teen Titans',
    'The Venture',
    'Big Mouth',
    'Universe',
    'My Little',
    'Archer',
    'Regular',
    'We Bare',
    'NinjaGo',
    'Moral Orel',
    'Phineas',
    'Randy',
  ],
};

const t_cartoon_characters: Theme = {
  name: 'Cartoon Characters',
  identifier: 'cartoon-characters',
  names: [
    'Donald',
    'Squidward',
    'Bender',
    'Leela',
    'Brian',
    'Velma',
    'Fred',
    'Tom',
    'Helga',
    'Rick',
    'Jerry',
    'Diego',
    'Stewie',
    'Sylvester',
    'Gumball',
    'Jake',
    'Darwin',
    'Daffy Duck',
    'Bugs Bunny',
    'Jake the Dog',
    'Daphne',
    'SpongeBob',
    'Sandy',
    'Tweety',
    'Pikachu',
    'Dora',
    'Popeye',
    'Dexter',
    'Shaggy',
    'Morty',
    'Ben 10',
    'Finn',
    'Mickey',
    'Fry',
    'Arnold',
    'Boots',
    'Scooby-Doo',
    'Patrick',
    'Yogi Bear',
    'Goofy',
  ],
};

const t_breaking_bad: Theme = {
  name: 'Breaking Bad',
  identifier: 'breaking-bad',
  names: [
    'Kim',
    'Francesca',
    'Saul',
    'Jimmy',
    'Victor',
    'Ernesto',
    'Marie',
    'Todd',
    'Walter',
    'Lydia',
    'Krazy-8',
    'Gus',
    'Skinny Pete',
    'Emilio',
    'Combo',
    'Mike',
    'Walt Jr.',
    'Chuck',
    'Nacho',
    'Jesse',
    'Skyler',
    'Badger',
    'Jane',
    'Hank',
    'Tuco',
    'Lalo',
    'Howard',
    'Gale',
    'Hector',
  ],
};

const t_got: Theme = {
  name: 'Game of Thrones',
  identifier: 'game-of-thrones',
  names: [
    'Oberyn',
    'Hodor',
    'Maester',
    'Tommen',
    'Melisandre',
    'Theon',
    'Bran',
    'Gendry',
    'Renly',
    'Olenna',
    'Grey Worm',
    'Cersei',
    'Brienne',
    'Samwell',
    'Davos',
    'Sansa',
    'Podrick',
    'Sandor',
    'Gilly',
    'Ramsay',
    'Roose',
    'Arya',
    'Tyrion',
    'Catelyn',
    'Tywin',
    'Stannis',
    'Shireen',
    'Daenerys',
    'Rickon',
    'Bronn',
    'Viserys',
    'Ygritte',
    'Jon Snow',
    'Joffrey',
    'Missandei',
    'Tormund',
    'Robb',
    'Jaime',
    'Margaery',
    'Varys',
    'Jorah',
  ],
};

const t_avatar: Theme = {
  name: 'Avatar The Last Airbender',
  identifier: 'atla',
  names: [
    'Ty Lee',
    'Kuei',
    'Aang',
    'Mai',
    'Pakku',
    'Momo',
    'Ozai',
    'June',
    'Iroh',
    'Haru',
    'Hama',
    'King Bumi',
    'Zuko',
    'Sokka',
    'Katara',
    'Toph',
    'Cabbage Man',
    'Appa',
    'Zhao',
    'Suki',
    'Jet',
    'Yue',
    'Jeong Jeong',
    'Bumi',
    'Hakoda',
    'Pipsqueak',
    'Azula',
    'Teo',
    'Long Feng',
    'Kanna',
  ],
};

const t_sopranos: Theme = {
  name: 'Sopranos',
  identifier: 'sopranos',
  names: [
    'Tony',
    'Paulie',
    'Silvio',
    'Junior',
    'Adriana',
    'Bobby',
    'Janice',
    'Meadow',
    'AJ',
    'Artie',
    'Carmine',
    'Ralph',
    'Patsy',
    'Hesh',
    'Livia',
    'Phil',
    'Gloria',
    'Feech',
    'Pussy',
    'Jackie',
  ],
};

const t_bluey: Theme = {
  name: 'Bluey',
  identifier: 'bluey',
  names: [
    'Indy',
    'Chatterbox',
    'Junior',
    'Teddy',
    'Socks',
    'Snickers',
    'Army',
    'Coco',
    'Bilby',
    'Bandit',
    'Mimi',
    'Jean-Luc',
    'Chilli',
    'Bingo',
    'Honey',
    'Rusty',
    'Fudge',
    'Bucky',
    'Baby Bat',
    'Muffin',
    'Bishop',
    'Buster',
    'Dumpy',
    'Calypso',
    'Bluey',
    'Mackenzie',
  ],
};

const t_rick_morty: Theme = {
  name: 'Rick and Morty',
  identifier: 'rick-and-morty',
  names: [
    'Pickle Rick',
    'Tammy',
    'Unity',
    'Beth Smith',
    'Snowball',
    'Summer',
    'Jerry Smith',
    'Morty',
    'Sleepy Gary',
    'Snuffles',
    'Noob-Noob',
    'Jerry',
    'Squanchy',
    'Birdperson',
    'Jessica',
    'Rick',
    'Mr. Needful',
    'Scary Terry',
    'Gearhead',
    'Beth',
    'Evil Morty',
  ],
};

const t_spongebob: Theme = {
  name: 'Spongebob',
  identifier: 'spongebob',
  names: [
    'Pearl',
    'Squidward',
    'Plankton',
    'Gary',
    'Flats',
    'Fred',
    'Patrick',
    'Man Ray',
    'Harold',
    'Mindy',
    'Patchy',
    'Potty',
    'Tom',
    'Kevin',
    'Larry',
    'Mermaid Man',
    'Bubble Bass',
    'DoodleBob',
    'Mrs. Puff',
    'SpongeBob',
    'Squilliam',
    'Mr. Krabs',
    'Sandy',
    'Karen',
    'Puff Mama',
    'Margaret',
    'Tina',
  ],
};

const t_family_guy: Theme = {
  name: 'Family Guy',
  identifier: 'family-guy',
  names: [
    'Opie',
    'Bruce',
    'Meg',
    'Loretta',
    'Peter',
    'Jasper',
    'New Brian',
    'Chris',
    'Bertram',
    'Herbert',
    'Lois',
    'Quagmire',
    'Brian',
    'Joe',
    'Cleveland',
    'Jesus',
    'Seamus',
    'Tom Tucker',
    'Mayor West',
    'Angela',
    'Stewie',
    'James Woods',
    'Bonnie',
    'Dr. Hartman',
    'Carter',
    'Jillian',
    'Death',
    'Megatron',
  ],
};

const t_office: Theme = {
  name: 'The Office',
  identifier: 'the-office',
  names: [
    'Jim',
    'Pam',
    'Michael',
    'Dwight',
    'Ryan',
    'Kelly',
    'Andy',
    'Kevin',
    'Angela',
    'Oscar',
    'Stanley',
    'Phyllis',
    'Creed',
    'Meredith',
    'Toby',
    'Jan',
    'David',
    'Darryl',
    'Roy',
    'Holly Flax',
    'Karen',
    'Erin Hannon',
    'Gabe Lewis',
    'Robert',
    'Jo Bennett',
    'Deangelo',
    'Charles',
    'Ryan Howard',
    'Danny',
    'Cece',
    'Mose',
    'Plop',
    'Nate',
    'Luke',
  ],
};

const t_the_boys: Theme = {
  name: 'The Boys',
  identifier: 'the-boys',
  names: [
    'Homelander',
    'Ezekiel',
    'A-Train',
    'Shockwave',
    'Frenchie',
    'Black',
    'Swatto',
    'Cindy',
    'Hughie',
    'Kimiko',
    'Starlight',
    'Queen',
    'Blindspot',
    'Gunpowder',
    "Mother's",
    'Popclaw',
    'Victoria',
    'Eagle',
    'Madelyn',
    'Mesmer',
    'The Deep',
    'Crimson',
    'Billy',
    'Stormfront',
    'Love',
    'Ashley',
  ],
};

const t_star_trek: Theme = {
  name: 'Star Trek',
  identifier: 'star-trek',
  names: [
    'Kirk',
    'Spock',
    'McCoy',
    'Scotty',
    'Uhura',
    'Sulu',
    'Chekov',
    'Picard',
    'Riker',
    'Data',
    'Worf',
    'La Forge',
    'Crusher',
    'Troi',
    'Wesley',
    'Janeway',
    'Chakotay',
    'Tuvok',
    'Paris',
    'Torres',
    'Seven',
    'Kim',
    'Archer',
    "T'Pol",
    'Trip',
    'Phlox',
    'Reed',
    'Sisko',
    'Kira',
    'Odo',
  ],
};

const t_stranger_things: Theme = {
  name: 'Stranger Things',
  identifier: 'stranger-things',
  names: [
    'Mind Flayer',
    'Brenner',
    'Demogorgon',
    'Kali',
    'Hopper',
    'Will',
    'Dart',
    'Dustin',
    'Mike',
    'Bob',
    'Jonathan',
    'Eleven',
    'Demodogs',
    'Lucas',
    'Erica',
    'Joyce',
    'Nancy',
    'Robin',
    'Steve',
    'Barb',
    'Billy',
    'Max',
    'Murray',
  ],
};

const t_regular_show: Theme = {
  name: 'Regular Show',
  identifier: 'regular-show',
  names: [
    'Mitch',
    'Thomas',
    'Doug',
    'Rigby',
    'Skips',
    'CJ',
    'Don',
    'Baby Ducks',
    'Susan',
    "Rigby's Mom",
    'Benson',
    'Mr. Ross',
    'Eileen',
    'Death',
    'Party Pete',
    'Mordecai',
    'Gene',
    'Pops',
    'Margaret',
    'Gary',
    'Dr. Henry',
    'Techmo',
    'Starla',
    'Muscle Man',
  ],
};

const t_i_carly: Theme = {
  name: 'iCarly',
  identifier: 'icarly',
  names: [
    'Mrs. Benson',
    'Shelby Marx',
    'Freddie',
    'Mandy',
    'Guppy',
    'Brad',
    'Gibby',
    'Jocelyn',
    'Carly',
    'Nora',
    'Nevel',
    'Ms. Briggs',
    'Pam Puckett',
    'Dak Zevon',
    'Lubert',
    'Sam',
    'Rona Burger',
    'Spencer',
    'Mr. Howard',
    'Mr. Galini',
    'Ginger Fox',
    'Lewbert',
    'Jeremy',
    'T-Bo',
    'Chuck',
    'Ricky Flame',
  ],
};

const c_television: Category = {
  name: 'Television 📺',
  language: 'EN',
  bgColor: '#CCCCCC',
  themes: [
    t_shows,
    t_tv_characters,
    t_cartoons,
    t_cartoon_characters,
    t_breaking_bad,
    t_got,
    t_avatar,
    t_sopranos,
    t_spongebob,
    t_bluey,
    t_family_guy,
    t_rick_morty,
    t_office,
    t_the_boys,
    t_stranger_things,
    t_regular_show,
    t_i_carly,
    t_star_trek,
  ],
};

//////////////////////////////////////////////
//////////////       All     /////////////////
//////////////////////////////////////////////

export const categories: Category[] = [
  c_misc,
  c_vegetation,
  c_food,
  c_drinks,
  c_mythology,
  c_locations,
  c_human_names,
  c_sports,
  c_items,
  c_movies,
  c_video_games,
  c_television,
];

export const themes: ThemesObject = categories.reduce<ThemesObject>((acc, category) => {
  category.themes.forEach((theme) => (acc[theme.identifier] = theme));
  return acc;
}, {});

export type Box = {
  [name: string]: {
    name: string;
    pokemon?: Pokemon;
  };
};

export function getNewBoxFromThemeTemplate(theme: Theme): Box {
  const box: Box = {};
  theme.names.forEach((name) => (box[name] = { name }));
  return box;
}
