import { Pokemon } from '../pokemon_data/definitions';
import { Category, Theme, ThemesObject } from './definitions';

//////////////////////////////////////////////
/////////       Misc Category     ////////////
//////////////////////////////////////////////

const t_colors: Theme = {
  identifier: 'colors',
  name: 'Colors',
  names: [
    'Azure',
    'Black',
    'Blue',
    'Brown',
    'Crimson',
    'Cyan',
    'Gold',
    'Green',
    'Indigo',
    'Ivory',
    'Jade',
    'Lavender',
    'Lilac',
    'Magenta',
    'Maroon',
    'Olive',
    'Orange',
    'Pink',
    'Purple',
    'Red',
    'Scarlet',
    'Silver',
    'Teal',
    'Turquoise',
    'White',
    'Amber',
    'Amethyst',
    'Aqua',
    'Blush',
    'Bronze',
    'Burgundy',
    'Canary',
    'Cerulean',
    'Charcoal',
    'Coral',
    'Emerald',
    'Fuchsia',
    'Garnet',
    'Hazel',
    'Mahogany',
    'Mint',
    'Peach',
    'Periwinkle',
    'Ruby',
    'Saffron',
    'Sapphire',
    'Sepia',
    'Topaz',
    'Vermilion',
    'Honeydew',
  ],
};

const t_emotions: Theme = {
  identifier: 'emotions',
  name: 'Emotions',
  names: [
    'Joy',
    'Sadness',
    'Anger',
    'Fear',
    'Surprise',
    'Love',
    'Anxiety',
    'Pride',
    'Guilt',
    'Hope',
    'Envy',
    'Relief',
    'Shame',
    'Despair',
    'Ecstasy',
    'Bliss',
    'Awe',
    'Grief',
    'Euphoria',
    'Chaos',
    'Trust',
    'Peace',
    'Zeal',
    'Charm',
    'Pity',
    'Rage',
    'Lust',
    'Glee',
    'Doubt',
    'Mirth',
    'Panic',
    'Rapture',
    'Elation',
    'Fury',
    'Sorrow',
    'Hate',
    'Shyness',
    'Shock',
  ],
};

const t_websites: Theme = {
  name: 'Websites',
  identifier: 'websites',
  names: [
    'Google',
    'Reddit',
    'Twitch',
    'Yahoo',
    'Bing',
    'Ask',
    'Quora',
    'Flickr',
    'AOL',
    'Vimeo',
    'eBay',
    'BBC',
    'CNN',
    'MSNBC',
    'Fox',
    'Hulu',
    'IMDb',
    'Zoom',
    'Zillow',
    'Paypal',
    'GitHub',
    'Slack',
    'Lyft',
    'Uber',
    'TikTok',
    'Spotify',
    'Pandora',
    'Skype',
    'Venmo',
    'Yelp',
    'Badoo',
    'Bumble',
    'WeChat',
    'Kakao',
    'LINE',
    'Viber',
    'Vine',
    'MeWe',
    'Plurk',
    'Stumble',
    'WordPress',
    'Blogger',
    'Tumblr',
    'Pinterest',
    'Mix',
    'Dribbble',
    'Discord',
    'Snapchat',
    'WhatsApp',
    'Telegram',
    'Trello',
    'Evernote',
    'Foursquare',
    'Meetup',
    'Goodreads',
    'Medium',
    'Behance',
    'DeviantArt',
    'SoundCloud',
    'Mixcloud',
    'Bandcamp',
    'Giphy',
    'Imgur',
    '9GAG',
    'BuzzFeed',
    'Chegg',
    'Udemy',
    'Coursera',
    'Khan',
    'Codecademy',
    'Duolingo',
    'Rosetta',
    'Skillshare',
    'Teachable',
    'Wattpad',
    'FanFiction',
    'AO3',
    'Fandom',
    'Wikia',
    'Twitch',
    'YouTube',
    'Netflix',
    'Prime',
    'Disney+',
    'HBO',
    'Showtime',
    'Starz',
    'Peacock',
    'Crave',
    'BritBox',
    'Paramount',
    'Shudder',
    'Curiosity',
    'Discovery',
    'Magellan',
    'Kanopy',
    'Mubi',
    'Dailymotion',
  ],
};

const t_apps: Theme = {
  name: 'Apps',
  identifier: 'apps',
  names: [
    'Snapchat',
    'Discord',
    'Spotify',
    'Tinder',
    'Twitter',
    'Uber',
    'YouTube',
    'Reddit',
    'Slack',
    'Zoom',
    'Venmo',
    'TikTok',
    'WhatsApp',
    'Hinge',
    'Signal',
    'Bumble',
    'Shazam',
    'WeChat',
    'Skype',
    'Trello',
    'Pinterest',
    'PayPal',
    'Instagram',
    'Messenger',
    'LinkedIn',
    'Netflix',
    'Waze',
    'Lyft',
    'DoorDash',
    'Gmail',
    'Outlook',
    'Evernote',
    'Dropbox',
    'Twitch',
    'eBay',
    'Amazon',
    'Kindle',
    'Fitbit',
    'Notion',
    'Asana',
    'Yelp',
    'Pandora',
    'SoundHound',
    'Audible',
    'Google',
    'Apple',
    'Facebook',
    'Quora',
    'Snap',
    'Clubhouse',
    'Telegram',
    'Zomato',
    'CashApp',
    'Robinhood',
    'N26',
    'Monzo',
    'Strava',
    'Nike',
    'MyFitness',
    'Duolingo',
    'Coursera',
    'Udemy',
    'KhanAcad',
    'Kahoot',
    'Flipgrid',
    'Minecraft',
    'AmongUs',
    'PUBG',
    'Roblox',
    'Fortnite',
    'CandyCrush',
    'TempleRun',
    'SubwaySur',
    'AngryBird',
    'WordsWF',
    'Tetris',
    'Sudoku',
    'Headspace',
    'Calm',
    'Smule',
    'Sing',
    'TuneIn',
    'Deezer',
    'Stitcher',
    'iHeart',
    'SoundCloud',
    'Anchor',
    'Podbean',
    'Buzzsprout',
    'RSSRadio',
    'Libsyn',
    'Castbox',
    'PocketCast',
    'Spreaker',
    'Breaker',
    'Overcast',
    'Simplecast',
    'ACast',
  ],
};

const t_ailments: Theme = {
  name: 'Ailments',
  identifier: 'ailments',
  names: [
    'Flu',
    'Cold',
    'Fever',
    'Cough',
    'Allergy',
    'Asthma',
    'Migraine',
    'Cancer',
    'Diabetes',
    'Ulcer',
    'Stroke',
    'Gout',
    'Anemia',
    'Arthritis',
    'Measles',
    'Mumps',
    'Tetanus',
    'Rabies',
    'Scabies',
    'Pox',
    'Jaundice',
    'Plague',
    'Malaria',
    'Cholera',
    'Leprosy',
    'Lupus',
    'Eczema',
    'Psoriasis',
    'Dengue',
    'Zika',
    'SARS',
    'MERS',
    'Polio',
    'Meningitis',
    'HIV',
    'AIDS',
    'Hepatitis',
    'Gonorrhea',
    'Syphilis',
    'Chickenpox',
    'Shingles',
    'Conjunctiva',
    'IBS',
    "Crohn's",
    'Epilepsy',
    "Parkinson's",
    "Alzheimer's",
    'Osteoporosis',
    'Glaucoma',
    'Cataract',
    'Bronchitis',
    'Pneumonia',
    'TB',
    'Whooping',
    'RSV',
    'Norovirus',
    'E. coli',
    'Salmonella',
    'Lyme',
    'Celiac',
    'Sprue',
    'Thalassemia',
    'SickleCell',
    'Hemophilia',
    'Cystic',
    'Fibrosis',
    'Hypothyroid',
    'Hyperthyroid',
    'Goiter',
    'Vitiligo',
    'Ringworm',
    'Herpes',
    'HPV',
    'Molluscum',
    'MRSA',
    'Toxoplasma',
    'Giardia',
    'Amoebiasis',
    'Trich',
    'Pinworm',
    'Ascariasis',
    'Hookworm',
    'Tapeworm',
    'Schisto',
    'Lymphoma',
    'Myeloma',
    'Melanoma',
    'Sarcoma',
    'Glioma',
    'Leukemia',
    'Carcinoma',
    'Myoma',
    'Fibroma',
    'Lipoma',
    'Adenoma',
    'Nodule',
    'Polyp',
    'Cyst',
    'Abscess',
    'Boil',
  ],
};

const t_animals: Theme = {
  name: 'Animals',
  identifier: 'animals',
  names: [
    'Tiger',
    'Lion',
    'Bear',
    'Wolf',
    'Fox',
    'Eagle',
    'Hawk',
    'Raven',
    'Crow',
    'Owl',
    'Snake',
    'Lizard',
    'Turtle',
    'Frog',
    'Toad',
    'Fish',
    'Shark',
    'Whale',
    'Dolphin',
    'Octopus',
    'Squid',
    'Crab',
    'Lobster',
    'Shrimp',
    'Scorpion',
    'Spider',
    'Ant',
    'Bee',
    'Butterfly',
    'Moth',
    'Dragonfly',
    'Ladybug',
    'Beetle',
    'Mantis',
    'Fly',
    'Mosquito',
    'Mule',
    'Horse',
    'Donkey',
    'Zebra',
    'Giraffe',
    'Elephant',
    'Rhino',
    'Hippo',
    'Buffalo',
    'Cow',
    'Bison',
    'Goat',
    'Sheep',
    'Pig',
    'Boar',
    'Deer',
    'Elk',
    'Moose',
    'Antelope',
    'Kangaroo',
    'Koala',
    'Panda',
    'Bear',
    'Monkey',
    'Gorilla',
    'Chimp',
    'Orangutan',
    'Sloth',
    'Bat',
    'Rat',
    'Mouse',
    'Squirrel',
    'Rabbit',
    'Hare',
    'Hedgehog',
    'Porcupine',
    'Badger',
    'Otter',
    'Beaver',
    'Seal',
    'SeaLion',
    'Walrus',
    'Penguin',
    'Parrot',
    'Eagle',
    'Hawk',
    'Falcon',
    'Ostrich',
    'Emu',
    'Pelican',
    'Swan',
    'Duck',
    'Goose',
  ],
};

const t_dog_breeds: Theme = {
  name: 'Dog Breeds',
  identifier: 'dog-breeds',
  names: [
    'Husky',
    'Labrador',
    'Retriever',
    'Poodle',
    'Bulldog',
    'Boxer',
    'Dalmatian',
    'Chihuahua',
    'Pug',
    'Beagle',
    'Rottweiler',
    'ShihTzu',
    'Doberman',
    'Corgi',
    'Schnauzer',
    'Collie',
    'GreatDane',
    'Akita',
    'Dachshund',
    'Greyhound',
    'Malamute',
    'Pomeranian',
    'Setter',
    'Shepherd',
    'Spaniel',
    'Terrier',
    'Whippet',
    'Bichon',
    'Mastiff',
    'Weimaraner',
    'Basset',
    'Cocker',
    'Samoyed',
    'Hound',
    'Papillon',
    'Borzoi',
    'Briard',
    'Elkhound',
    'Finnish',
    'Griffon',
    'Ibizan',
    'Keeshond',
    'Komondor',
    'Leonberg',
    'Lhasa Apso',
    'Lowchen',
    'Pointer',
    'Saluki',
    'Schipperke',
    'Shiba',
    'Vizsla',
    'Yorkshire',
  ],
};

const t_birds: Theme = {
  name: 'Birds',
  identifier: 'birds',
  names: [
    'Eagle',
    'Hawk',
    'Raven',
    'Crow',
    'Owl',
    'Falcon',
    'Sparrow',
    'Robin',
    'Jay',
    'Cardinal',
    'Bluejay',
    'Humming',
    'Swallow',
    'Swift',
    'Dove',
    'Pigeon',
    'Woodpeck',
    'Parrot',
    'Macaw',
    'Cockatoo',
    'Canary',
    'Finch',
    'Toucan',
    'Pelican',
    'Albatross',
    'Seagull',
    'Penguin',
    'Ostrich',
    'Emu',
    'Flamingo',
    'Swan',
    'Goose',
    'Duck',
    'Egret',
    'Stork',
    'Heron',
    'Crane',
    'Ibis',
    'Kiwi',
    'Magpie',
    'Mynah',
    'Starling',
    'Thrasher',
    'Quail',
    'Cockatiel',
    'Lark',
    'Grebe',
    'Puffin',
    'Kingfisher',
    'Osprey',
    'Kite',
    'Goshawk',
    'Sparrow',
    'Bluebird',
    'Eagle',
  ],
};

const t_fish: Theme = {
  name: 'Fish',
  identifier: 'fish',
  names: [
    'Shark',
    'Whale',
    'Dolphin',
    'Tuna',
    'Salmon',
    'Trout',
    'Cod',
    'Bass',
    'Perch',
    'Pike',
    'Carp',
    'Catfish',
    'Guppy',
    'Goldfish',
    'Angelfish',
    'Swordfish',
    'Marlin',
    'Mackerel',
    'Herring',
    'Sardine',
    'Anchovy',
    'Eel',
    'Sturgeon',
    'Piranha',
    'Barracuda',
    'Mullet',
    'MahiMahi',
    'Halibut',
    'Flounder',
    'Sole',
    'Grouper',
    'Tilefish',
    'Trigger',
    'Clownfish',
    'Tang',
    'Surgeon',
    'Butterfly',
    'Puffer',
    'Blowfish',
    'Octopus',
    'Squid',
    'Cuttlefish',
    'Shrimp',
    'Crab',
    'Lobster',
    'Oyster',
    'Clam',
    'Mussel',
    'Scallop',
    'Snail',
    'Barnacle',
    'Starfish',
    'SeaUrchin',
    'Jellyfish',
    'Sponge',
    'SeaCucumber',
    'Seahorse',
    'SeaDragon',
  ],
};

const t_bugs: Theme = {
  name: 'Bugs',
  identifier: 'bugs',
  names: [
    'Beetle',
    'Ant',
    'Spider',
    'Fly',
    'Mosquito',
    'Wasp',
    'Bee',
    'Butterfly',
    'Moth',
    'Dragonfly',
    'Ladybug',
    'Grasshop',
    'Cicada',
    'Cricket',
    'Centipede',
    'Millipede',
    'Scorpion',
    'Tarantula',
    'Tick',
    'Flea',
    'Earwig',
    'Praying',
    'Mantis',
    'Walking',
    'Stick',
    'Firefly',
    'Glowworm',
    'Beetle',
    'Stinkbug',
    'Dungbeetl',
    'Leafbug',
    'Waterbug',
    'Rhinocero',
    'Hercules',
    'Beetle',
    'Atlas',
    'Moth',
    'Silkmoth',
    'Luna',
    'Moth',
    'Swallowtail',
    'Caterpillar',
    'Worm',
    'Weevil',
    'Snail',
    'Slug',
    'Cockroach',
    'Cicada',
    'Antlion',
    'Pillbug',
    'Crab',
    'Louse',
    'Termite',
    'Aphid',
    'Hornet',
    'Grub',
    'Dobsonfly',
    'Mayfly',
    'Diving',
    'Beetle',
  ],
};

const t_occupations: Theme = {
  name: 'Occupations',
  identifier: 'occupations',
  names: [
    'Doctor',
    'Nurse',
    'Teacher',
    'Engineer',
    'Artist',
    'Actor',
    'Writer',
    'Singer',
    'Farmer',
    'Chef',
    'Police',
    'Lawyer',
    'Judge',
    'Firefighter',
    'Pilot',
    'Soldier',
    'Driver',
    'Dancer',
    'Designer',
    'Scientist',
    'Athlete',
    'Painter',
    'Musician',
    'Architect',
    'Carpenter',
    'Plumber',
    'Electric',
    'Gardener',
    'Librarian',
    'Tailor',
    'Mechanic',
    'Veterin',
    'Zookeeper',
    'Photographer',
    'Editor',
    'Journalist',
    'Director',
    'Producer',
    'Animator',
    'Consultant',
    'Advisor',
    'Economist',
    'Psycholog',
    'Therapist',
    'Physicist',
    'Biologist',
    'Chemist',
    'Geologist',
    'Historian',
    'Philosoph',
    'Sociolog',
    'Anthropol',
    'Linguist',
    'Mathemat',
    'Statistic',
    'Actuary',
    'Broker',
    'Banker',
    'Investor',
    'Trader',
    'Entrepre',
    'Marketer',
    'Salesman',
    'Consultor',
    'Publicist',
    'Accountant',
    'Auditor',
    'Bookkeep',
    'Reception',
    'Secretary',
    'Assistant',
    'Assistant',
    'Reporter',
    'Conductor',
    'Stewardess',
    'Trolley',
    'Brakeman',
    'Cabin',
    'Attendant',
    'Dispatcher',
    'Porter',
    'Agent',
    'Ambassador',
    'Director',
    'Bishop',
    'Nun',
    'Chaplain',
  ],
};

const t_technical_terms: Theme = {
  name: 'Technical Terms',
  identifier: 'technical-terms',
  names: [
    'Motherboard',
    'Bluetooth',
    'VPN',
    'USB',
    'Firewall',
    'Ethernet',
    'Router',
    'Gateway',
    'Server',
    'Client',
    'Database',
    'Cache',
    'Algorithm',
    'Encryption',
    'Decryption',
    'Compiler',
    'Debugger',
    'Framework',
    'Library',
    'API',
    'Interface',
    'Protocol',
    'DNS',
    'IPaddress',
    'Hostname',
    'Domain',
    'Subnet',
    'LAN',
    'WAN',
    'Internet',
    'Cloud',
    'Backup',
    'Restore',
    'Monitor',
    'Keyboard',
    'Mouse',
    'Scanner',
    'Printer',
    'Speaker',
    'Microphone',
    'Camera',
    'Modem',
    'Processor',
    'Memory',
    'Storage',
    'Harddisk',
    'SSD',
    'RAM',
    'Graphics',
    'GPU',
    'CPU',
    'BIOS',
    'Firmware',
    'Driver',
    'Pixel',
    'Resolution',
    'Bandwidth',
    'Latency',
    'Ping',
    'Packet',
  ],
};

const t_crimes: Theme = {
  name: 'Crimes',
  identifier: 'crimes',
  names: [
    'Theft',
    'Robbery',
    'Assault',
    'Murder',
    'Arson',
    'Fraud',
    'Forgery',
    'Extortion',
    'Kidnap',
    'Hijack',
    'Smuggle',
    'Embezzle',
    'Perjury',
    'Bribery',
    'Blackmail',
    'Stalking',
    'Vandalism',
    'Mugging',
    'Shoplift',
    'Harass',
    'Sabotage',
    'Espionage',
    'Launder',
    'Racketeer',
    'Felony',
    'Pyramid',
    'Battery',
    'Piracy',
    'Slander',
    'Libel',
    'Rob',
    'Pillage',
    'Drugs',
    'Theft',
    'Poach',
    'Fraud',
    'Graft',
    'Swindle',
    'Scam',
    'Rustle',
    'Bootleg',
    'Cheat',
    'Hack',
  ],
};

const t_general_brands: Theme = {
  name: 'General Brands',
  identifier: 'general-brands',
  names: [
    'Apple',
    'Microsoft',
    'Samsung',
    'Sony',
    'Google',
    'Toyota',
    'Honda',
    'Nike',
    'Adidas',
    'Puma',
    'Reebok',
    'Canon',
    'Nikon',
    'Panasonic',
    'LG',
    'Mitsubishi',
    'Bose',
    'Philips',
    'Dell',
    'HP',
    'Lenovo',
    'Acer',
    'Asus',
    'Alienware',
    'Fujitsu',
    'Toshiba',
    'Sharp',
    'JVC',
    'Hewlett',
    'Packard',
    'Corsair',
    'Western',
    'Digital',
    'Seagate',
    'Logitech',
    'SteelSeries',
    'Razer',
    'Vizio',
    'Brother',
    'Epson',
    'Xerox',
    'Lexmark',
    'Verizon',
    'ATandT',
    'Sprint',
    'T-Mobile',
    'Qualcomm',
    'Intel',
    'AMD',
    'ARM',
    'Cisco',
    'Linksys',
    'Netgear',
    'Belkin',
    'Ubiquiti',
    'Sennheiser',
    'Plantronics',
    'Garmin',
    'Western',
    'Union',
    'Mastercard',
    'Visa',
    'PayPal',
    'American',
    'Express',
    'Capital',
    'One',
    'HSBC',
    'Citibank',
    'Barclays',
    'TD',
    'Bank',
    'Scotiabank',
    'ING',
    'Credit',
    'Ameritrade',
    'Charles',
    'Schwab',
    'Fidelity',
    'Vanguard',
    'BlackRock',
    'Goldman',
    'Sachs',
    'Morgan',
    'Stanley',
    'UBS',
    'Deutsche',
    'Bank',
    'BNP',
    'Paribas',
    'Societe',
    'Generale',
    'UBS',
    'Nomura',
    'Merrill',
    'Lynch',
    'JPMorgan',
    'Chase',
  ],
};

const c_misc: Category = {
  name: 'Misc 🐶',
  language: 'EN',
  bgColor: '#00A96E',
  themes: [
    t_colors,
    t_emotions,
    t_websites,
    t_apps,
    t_ailments,
    t_animals,
    t_dog_breeds,
    t_birds,
    t_fish,
    t_bugs,
    t_occupations,
    t_technical_terms,
    t_crimes,
    t_general_brands,
  ],
};

//////////////////////////////////////////////
///////       Vegetation Category     ////////
//////////////////////////////////////////////

const t_plants: Theme = {
  name: 'Plants',
  identifier: 'plants',
  names: [
    'Rose',
    'Lily',
    'Daisy',
    'Tulip',
    'Poppy',
    'Sunflower',
    'Violet',
    'Jasmine',
    'Orchid',
    'Pansy',
    'Peony',
    'Iris',
    'Blossom',
    'Petunia',
    'Fern',
    'Lavender',
    'Holly',
    'Maple',
    'Juniper',
    'Birch',
    'Willow',
    'Cypress',
    'Alder',
    'Pine',
    'Acacia',
    'Bamboo',
    'Cedar',
    'Oak',
    'Ash',
    'Hazel',
    'Magnolia',
    'Rosemary',
    'Thyme',
    'Basil',
    'Sage',
    'Mint',
    'Lemon',
    'Cherry',
    'Apple',
    'Plum',
    'Pear',
    'Peach',
    'Fig',
    'Grape',
    'Kiwi',
    'Melon',
    'Cactus',
    'Aloe',
    'Dandelion',
    'Clover',
    'Moss',
    'Sequoia',
    'Ficus',
    'Palm',
    'Bonsai',
    'Lotus',
    'Hyacinth',
    'Mimosa',
    'Azalea',
    'Camellia',
    'Daffodil',
    'Gladiolus',
    'Marigold',
    'Narcissus',
    'Zinnia',
    'Carnation',
    'Dahlia',
    'Eucalyptus',
    'Gardenia',
    'Hibiscus',
    'Jasmine',
    'Lilac',
    'Magnolia',
    'Morning',
    'Glory',
    'Primrose',
    'Snapdragon',
    'Sweetpea',
    'Wisteria',
    'Yarrow',
    'Yucca',
  ],
};

const t_flowers: Theme = {
  name: 'Flowers',
  identifier: 'flowers',
  names: [
    'Rose',
    'Lily',
    'Daisy',
    'Tulip',
    'Poppy',
    'Sunflower',
    'Violet',
    'Jasmine',
    'Orchid',
    'Pansy',
    'Peony',
    'Iris',
    'Blossom',
    'Petunia',
    'Lavender',
    'Hollyhock',
    'Marigold',
    'Carnation',
    'Daffodil',
    'Dahlia',
    'Zinnia',
    'Camellia',
    'Gladiolus',
    'Magnolia',
    'Hyacinth',
    'Azalea',
    'Dandelion',
    'Freesia',
    'Geranium',
    'Lotus',
    'Morning',
    'Glory',
    'Primrose',
    'Snapdragon',
    'Sweetpea',
    'Wisteria',
    'Yarrow',
    'Begonia',
    'Clematis',
    'Fuchsia',
    'Hibiscus',
    'Lilac',
    'Nasturtium',
    'Anemone',
    'Bluebell',
    'Foxglove',
    'Jonquil',
    'Larkspur',
    'Snowdrop',
    'Thistle',
    'Verbena',
    'Aster',
    'Buttercup',
    'Cowslip',
    'Heather',
  ],
};

const t_trees: Theme = {
  name: 'Trees',
  identifier: 'trees',
  names: [
    'Oak',
    'Maple',
    'Birch',
    'Willow',
    'Cedar',
    'Pine',
    'Ash',
    'Alder',
    'Juniper',
    'Acacia',
    'Beech',
    'Cypress',
    'Elm',
    'Fir',
    'Hickory',
    'Mahogany',
    'Poplar',
    'Redwood',
    'Sycamore',
    'Spruce',
    'Walnut',
    'Cherry',
    'Chestnut',
    'Eucalyptus',
    'Hemlock',
    'Magnolia',
    'Palm',
    'Bamboo',
    'Baobab',
    'Bonsai',
    'Banyan',
    'Douglas',
    'Ficus',
    'Ginkgo',
    'Linden',
    'Mango',
    'Olive',
    'Papaya',
    'Rubber',
    'Sandalwood',
    'Teak',
    'Yew',
    'Zelkova',
    'Almond',
    'Avocado',
    'Buckeye',
    'Catalpa',
    'Dogwood',
    'Elder',
    'Hackberry',
    'Locust',
    'Mulberry',
    'Rowan',
    'Sassafras',
    'Tamarind',
    'Viburnum',
    'Wisteria',
    'Yucca',
  ],
};

const t_aquatic_plants: Theme = {
  name: 'Aquatic Plants',
  identifier: 'aquatic-plants',
  names: [
    'Seagrass',
    'Kelp',
    'Seaweed',
    'Algae',
    'Waterlily',
    'Cattail',
    'Duckweed',
    'Waterfern',
    'Watercress',
    'Pondweed',
    'Waterwort',
    'Coralwort',
    'Anemone',
    'Starwort',
    'Watermint',
    'Sealily',
    'Coralweed',
    'Sealwort',
    'Seagrass',
    'Algaegrass',
    'Seaweed',
    'Waterlily',
    'Cattail',
    'Duckweed',
    'Waterfern',
  ],
};

const c_vegetation: Category = {
  name: 'Vegetation 🌼',
  language: 'EN',
  bgColor: '#78932C',
  themes: [t_plants, t_flowers, t_trees, t_aquatic_plants],
};

//////////////////////////////////////////////
/////////       Food Category     ////////////
//////////////////////////////////////////////

const t_food: Theme = {
  identifier: 'food',
  name: 'Food',
  names: [
    'BBQ',
    'Biscuit',
    'Burger',
    'Calzone',
    'Casserole',
    'Chowder',
    'Cornbread',
    'Curry',
    'Dango',
    'Dumpling',
    'Eggroll',
    'Falafel',
    'Frittata',
    'Fudge',
    'Gumbo',
    'Hotcake',
    'Lasagna',
    'Meatball',
    'Muffin',
    'Omelette',
    'Pancake',
    'Pasta',
    'Pastry',
    'Pavlova',
    'Pizza',
    'Polenta',
    'Popcorn',
    'Pretzel',
    'Quiche',
    'Risotto',
    'Salami',
    'Sausage',
    'Shawarma',
    'Skewer',
    'Soup',
    'Souvlaki',
    'Spaghetti',
    'Steak',
    'Stew',
    'Sushi',
    'Taco',
    'Tempura',
    'Tiramisu',
    'Toast',
    'Toffee',
    'Tortilla',
    'Waffle',
    'Wonton',
    'Yakitori',
  ],
};

const t_fruit: Theme = {
  name: 'Fruit',
  identifier: 'fruit',
  names: [
    'Apple',
    'Banana',
    'Cherry',
    'Grape',
    'Orange',
    'Mango',
    'Peach',
    'Pear',
    'Plum',
    'Kiwi',
    'Melon',
    'Papaya',
    'Lemon',
    'Lime',
    'Fig',
    'Grapefruit',
    'Apricot',
    'Pineapple',
    'Coconut',
    'Cranberry',
    'Blueberry',
    'Raspberry',
    'Strawberry',
    'Blackberry',
    'Watermelon',
    'Guava',
    'Lychee',
    'Nectarine',
    'Clementine',
    'Tangerine',
    'Starfruit',
    'Persimmon',
    'Cantaloupe',
    'Honeydew',
    'Mulberry',
    'Cherimoya',
    'Durian',
    'Figs',
    'Pears',
    'Apricots',
    'Custard',
    'Jelly',
    'Avocado',
    'Chili',
    'Mango',
    'Açaí',
    'Soursop',
    'Feijoa',
  ],
};

const t_veggies: Theme = {
  name: 'Veggies',
  identifier: 'veggies',
  names: [
    'Carrot',
    'Tomato',
    'Potato',
    'Broccoli',
    'Spinach',
    'Cabbage',
    'Pepper',
    'Lettuce',
    'Radish',
    'Onion',
    'Celery',
    'Pumpkin',
    'Zucchini',
    'Eggplant',
    'Cucumber',
    'Garlic',
    'Turnip',
    'Kale',
    'Beetroot',
    'Artichoke',
    'Asparagus',
    'Brussels',
    'Sprout',
    'Peas',
    'Mushroom',
    'Bean',
    'Squash',
    'Leek',
    'Yam',
    'Okra',
    'Rutabaga',
    'Fennel',
    'Ginger',
    'Chili',
    'Soybean',
    'Chard',
    'Bokchoy',
    'Endive',
    'Arugula',
    'Parsnip',
    'Scallion',
    'Chicory',
    'Jicama',
    'Lentil',
    'Mungbean',
    'Radish',
    'Salsify',
    'Skirret',
    'Taro',
    'Tatsoi',
    'Yardlong',
    'Zucchini',
  ],
};

const t_meats: Theme = {
  name: 'Meats',
  identifier: 'meats',
  names: [
    'Beef',
    'Pork',
    'Lamb',
    'Venison',
    'Chicken',
    'Turkey',
    'Duck',
    'Quail',
    'Goose',
    'Rabbit',
    'Bison',
    'Elk',
    'Boar',
    'Ostrich',
    'Emu',
    'Kangaroo',
    'Horse',
    'Lobster',
    'Crab',
    'Shrimp',
    'Cod',
    'Salmon',
    'Tuna',
    'Trout',
    'Bass',
    'Haddock',
    'Sardine',
    'Mackerel',
    'Anchovy',
    'Herring',
  ],
};

const t_condiments: Theme = {
  name: 'Condiments',
  identifier: 'condiments',
  names: [
    'Salt',
    'Pepper',
    'Mustard',
    'Ketchup',
    'Mayonnaise',
    'Soy Sauce',
    'Vinegar',
    'Honey',
    'Sriracha',
    'Relish',
    'Tabasco',
    'Wasabi',
    'BBQ Sauce',
    'Teriyaki',
    'Tartar',
    'Pesto',
    'Chutney',
    'Salsa',
    'Guacamole',
    'Hummus',
    'Aioli',
    'Marmite',
    'Kimchi',
    'Harissa',
    'Tahini',
  ],
};

const t_spices: Theme = {
  name: 'Spices',
  identifier: 'spices',
  names: [
    'Clove',
    'Cumin',
    'Paprika',
    'Cinnamon',
    'Saffron',
    'Nutmeg',
    'Ginger',
    'Cardamom',
    'Turmeric',
    'Chili',
    'Pepper',
    'Garlic',
    'Basil',
    'Thyme',
    'Rosemary',
    'Oregano',
    'Sage',
    'Parsley',
    'Dill',
    'Fennel',
    'Anise',
    'Caraway',
    'Chives',
    'Allspice',
    'Celery',
    'Mustard',
    'Sumac',
    'Tarragon',
    'Juniper',
    'Bay Leaf',
  ],
};

const t_sweets: Theme = {
  name: 'Sweets',
  identifier: 'sweets',
  names: [
    'Candy',
    'Cookie',
    'Brownie',
    'Muffin',
    'Fudge',
    'Toffee',
    'Caramel',
    'Truffle',
    'Bonbon',
    'Pudding',
    'Gelato',
    'Sorbet',
    'Sherbet',
    'Cupcake',
    'Macaron',
    'Eclair',
    'Donut',
    'Churro',
    'Tiramisu',
    'Mousse',
    'Pancake',
    'Waffle',
    'Scone',
    'Marshy',
    'Frosty',
    'Nougat',
    'ChocIce',
    'Cannoli',
    'Fondue',
    'Praline',
    'Gelato',
    'Biscuit',
    'Doughnut',
    'Frosting',
    'Jellybean',
    'Lollipop',
    'Macaroon',
    'Meringue',
    'Popsicle',
    'Snowcone',
    'Sorbet',
    'Souffle',
    'Sundae',
  ],
};

const t_candy: Theme = {
  name: 'Candy',
  identifier: 'candy',
  names: [
    'Candy',
    'Gummy',
    'Skittles',
    'Twizzler',
    'Snickers',
    'KitKat',
    'Reese',
    'Mentos',
    'Jellybean',
    'M&M',
    'Lollipop',
    'Tootsie',
    'SourPatch',
    'MilkyWay',
    'Nerds',
    'Peppermint',
    'Jawbreaker',
    'Bubblegum',
    'Licorice',
    'Smarties',
    'Caramel',
    'RockCandy',
    'PixyStix',
    'AlmondJoy',
    'PopRocks',
    'Pez',
    'SweeTarts',
    'CandyCorn',
    'Snickers',
    'Twix',
    'Gobstopper',
    'RingPop',
    'AirHead',
    'Dots',
    'HubbaBubba',
    'Warheads',
    'Hershey',
    'SourPatch',
  ],
};

const t_snacks: Theme = {
  name: 'Snacks',
  identifier: 'snack',
  names: [
    'Chip',
    'Pretzel',
    'Popcorn',
    'Nacho',
    'Cheetos',
    'Doritos',
    'Fritos',
    'CheezIt',
    'Ritz',
    'Oreo',
    'Twinkie',
    'Pringle',
    'Granola',
    'Raisin',
    'Peanut',
    'Cashew',
    'Pistachio',
    'Almonds',
    'Walnut',
    'Pecan',
    'Macadamia',
    'TrailMix',
    'Sunflower',
    'FruitSnack',
    'Fruit',
    'Leather',
    'BeefJerky',
    'RiceCake',
    'CerealBar',
    'PopTart',
    'FruitRollUp',
    'Graham',
    'AnimalCracker',
    'GranolaBar',
    'Pocky',
    'Nutella',
    'Gelatin',
    'Popsicle',
    'IceCream',
    'Sandwich',
    'Milkshake',
    'Yogurt',
    'Bagel',
    'Chips',
    'Fruit',
    'Cookie',
  ],
};

const t_cheese: Theme = {
  name: 'Cheese',
  identifier: 'cheese',
  names: [
    'Cheddar',
    'Gouda',
    'Brie',
    'Feta',
    'Parmesan',
    'Mozzarella',
    'Gorgonzola',
    'Camembert',
    'Colby',
    'Havarti',
    'Provolone',
    'Edam',
    'Fontina',
    'Ricotta',
    'Manchego',
    'Muenster',
    'Emmental',
    'Jarlsberg',
    'Pepperjack',
    'Gruyere',
    'GoatCheese',
    'BlueCheese',
    'Limburger',
  ],
};

const t_restaurants: Theme = {
  name: 'Restaurants',
  identifier: 'restaurants',
  names: [
    'McDonalds',
    'BurgerKing',
    'Starbucks',
    'Subway',
    'Wendys',
    'Chipotle',
    'TacoBell',
    'PizzaHut',
    'Dominos',
    'KFC',
    'Panera',
    'ChickFilA',
    'Dunkin',
    'FiveGuys',
    'PandaExprs',
    'InNOut',
    'Arbys',
    'JimmyJohns',
    'LittleCsrs',
    'JackBox',
    'CarlJr',
    'Cheesecake',
    'OliveGarden',
    'RedLobster',
    'BDubs',
    'LongJohns',
    'TexasRoad',
    'SaltGrass',
    'RedRobin',
    'Chilis',
    'RubyTuesday',
    'Outback',
    'Dennys',
    'PFChangs',
    'Applebees',
    'Carrabbas',
    'Bonefish',
    'YardHouse',
    'BahamaBree',
    'Maggianos',
    'Fogo',
    'Seasons52',
    'Brio',
    'OCharleys',
    'BJs',
  ],
};

const c_food: Category = {
  name: 'Food 🍟',
  language: 'EN',
  bgColor: '#F03A17',
  themes: [
    t_food,
    t_fruit,
    t_veggies,
    t_meats,
    t_condiments,
    t_spices,
    t_sweets,
    t_candy,
    t_snacks,
    t_cheese,
    t_restaurants,
  ],
};

//////////////////////////////////////////////
/////////       Drinks Category     //////////
//////////////////////////////////////////////

const t_drinks: Theme = {
  name: 'Drinks',
  identifier: 'drinks',
  names: [
    'Coffee',
    'Tea',
    'Latte',
    'Espresso',
    'Mocha',
    'Cappuccino',
    'Macchiato',
    'Americano',
    'Smoothie',
    'Juice',
    'Lemonade',
    'Soda',
    'Cola',
    'RootBeer',
    'Sprite',
    'Pepsi',
    'Mountain',
    'Dew',
    'Fanta',
    'Gatorade',
    'Powerade',
    'RedBull',
    'Monster',
    'Rockstar',
    'Juice',
    'Energy',
    'Drink',
    'Water',
    'Seltzer',
    'Beer',
    'Ale',
    'Lager',
    'Stout',
    'Porter',
    'Pilsner',
    'Wine',
    'Merlot',
    'Pinot',
    'Grigio',
    'Cabernet',
    'Sauvignon',
    'Champagne',
    'Mimosa',
    'Margarita',
    'Martini',
    'Whiskey',
    'Vodka',
  ],
};

const t_drink_brands: Theme = {
  name: 'Drink Brands',
  identifier: 'drink-brands',
  names: [
    'Coke',
    'Pepsi',
    'Sprite',
    'Fanta',
    'RedBull',
    'Monster',
    'Rockstar',
    'Gatorade',
    'Powerade',
    'Aquafina',
    'Dasani',
    'Evian',
    'Perrier',
    'SanPellegr',
    'Starbucks',
    'Nespresso',
    'Lipton',
    'Tropicana',
    'OceanSpray',
    'MinuteMaid',
    'Welchs',
    'VitaminWater',
    'Arizona',
    'Snapple',
    'Sobe',
    'Glaceau',
    'Xyience',
    'Propel',
    'Fuze',
  ],
};

const t_soda: Theme = {
  name: 'Soda',
  identifier: 'soda',
  names: [
    'Coke',
    'Pepsi',
    'Sprite',
    'Fanta',
    'DrPepper',
    'MountainDw',
    '7Up',
    'RootBeer',
    'Sunkist',
    'DietCoke',
    'CanadaDry',
    'Schweppes',
    'AandW',
    'MelloYellw',
    'PibbXtra',
    'Fresca',
    'Crush',
    'Barqs',
    'SierraMist',
    'Squirt',
    'BigRed',
    'CreamSoda',
    'SunDrop',
    'IBC',
    'CherryCoke',
    'RC',
    'Jones',
    'Shasta',
    'Jarritos',
    'Boylan',
  ],
};

const t_tea: Theme = {
  name: 'Tea',
  identifier: 'tea',
  names: [
    'GreenTea',
    'BlackTea',
    'Oolong',
    'WhiteTea',
    'EarlGrey',
    'ChaiTea',
    'JasmineTea',
    'Matcha',
    'HerbalTea',
    'Peppermint',
    'Chamomile',
    'Rooibos',
    'Genmaicha',
    'Hojicha',
    'Sencha',
    'PuErh',
    'YerbaMate',
    'Lapsang',
    'Assam',
  ],
};

const t_coffee: Theme = {
  name: 'Coffee',
  identifier: 'coffee',
  names: [
    'Espresso',
    'Latte',
    'Cappuccino',
    'Mocha',
    'Americano',
    'Macchiato',
    'FlatWhite',
    'Affogato',
    'Turkish',
    'Irish',
    'Vienna',
    'Doppio',
    'Ristretto',
    'Cortado',
    'Breve',
    'ColdBrew',
    'Instant',
    'Decaf',
    'Nitro',
    'Pourover',
    'Aeropress',
    'Espresso',
    'Lungo',
    'RedEye',
    'Cubano',
    'Phin',
  ],
};

const t_cocktails: Theme = {
  name: 'Cocktails',
  identifier: 'cocktails',
  names: [
    'Martini',
    'Margarita',
    'Daiquiri',
    'Mojito',
    'Cosmopoli',
    'Negroni',
    'Manhattan',
    'OldFashion',
    'MaiTai',
    'BloodyMary',
    'MoscowMule',
    'PinaColada',
    'Sazerac',
    'WhiskeySo',
    'Gimlet',
    'Bellini',
    'Caipirinha',
    'TomCollins',
    'Paloma',
    'Singapore',
    'Sling',
    'Sidecar',
    'Mimosa',
    'Martinez',
    'Julep',
    'Mule',
    'HotToddy',
    'Spritz',
  ],
};

const t_starbucks_drinks: Theme = {
  name: 'Starbucks Drinks',
  identifier: 'starbucks-drinks',
  names: [
    'Latte',
    'Cappuccino',
    'Macchiato',
    'Americano',
    'Mocha',
    'Espresso',
    'Teavana',
    'Refresher',
    'FlatWhite',
    'Nitro',
    'ColdBrew',
    'ChaiLatte',
    'IcedCoffee',
    'PikePlace',
    'Vanilla',
    'Caramel',
    'JavaChip',
    'GreenTea',
    'PinkDrink',
  ],
};

const c_drinks: Category = {
  name: 'Drinks 🍺',
  language: 'EN',
  bgColor: '#C98D43',
  themes: [t_drinks, t_drink_brands, t_soda, t_tea, t_coffee, t_cocktails, t_starbucks_drinks],
};

//////////////////////////////////////////////
///////       Mythology Category     /////////
//////////////////////////////////////////////

const t_norse_mythology: Theme = {
  identifier: 'norse-mythology',
  name: 'Norse Mythology',
  names: [
    'Thor',
    'Freya',
    'Loki',
    'Odin',
    'Baldr',
    'Frigg',
    'Tyr',
    'Saga',
    'Eir',
    'Skadi',
    'Sif',
    'Hel',
    'Vidar',
    'Njord',
    'Idun',
    'Fenrir',
    'Freyr',
    'Heimdall',
    'Ran',
    'Hermod',
    'Bragi',
    'Forseti',
    'Gerda',
    'Hoder',
    'Hodur',
    'Magni',
    'Modi',
    'Sigyn',
    'Sleipnir',
    'Sol',
    'Vali',
    'Ve',
    'Vili',
    'Angrboda',
    'Alviss',
    'Edda',
    'Fafnir',
    'Grid',
    'Hati',
    'Hlin',
    'Jord',
    'Mimir',
    'Nerthus',
    'Skoll',
    'Thrud',
    'Ullr',
    'Var',
    'Ymir',
  ],
};

const t_greek_mythology: Theme = {
  identifier: 'greek-mythology',
  name: 'Greek Mythology',
  names: [
    'Zeus',
    'Hera',
    'Poseidon',
    'Demeter',
    'Athena',
    'Apollo',
    'Artemis',
    'Ares',
    'Hermes',
    'Dionysus',
    'Persephone',
    'Hades',
    'Perseus',
    'Jason',
    'Odysseus',
    'Achilles',
    'Theseus',
    'Orpheus',
    'Icarus',
    'Medusa',
    'Circe',
    'Pandora',
    'Electra',
    'Echo',
    'Narcissus',
    'Pan',
    'Atlas',
    'Hector',
    'Paris',
    'Helen',
    'Cassandra',
    'Ariadne',
    'Calypso',
    'Nike',
    'Iris',
    'Hestia',
    'Eros',
    'Chaos',
    'Chiron',
    'Eurus',
    'Selene',
    'Triton',
    'Uranus',
    'Cronus',
    'Rhea',
    'Gaia',
    'Phoebe',
    'Janus',
  ],
};

const t_egyptian_mythology: Theme = {
  identifier: 'egyptian-mythology',
  name: 'Egyptian Mythology',
  names: [
    'Ra',
    'Isis',
    'Osiris',
    'Horus',
    'Anubis',
    'Thoth',
    'Bastet',
    'Sekhmet',
    'Set',
    'Amun',
    'Nut',
    'Maat',
    'Ptah',
    'Hathor',
    'Anhur',
    'Khnum',
    'Wadjet',
    'Sobek',
    'Bast',
    'Anuket',
    'Atum',
    'Neith',
    'Khonsu',
    'Mut',
    'Tefnut',
    'Khepri',
    'Seshat',
    'Serapis',
    'Nephthys',
    'Hapi',
    'Apis',
    'Osiris',
    'Horus',
    'Anubis',
    'Thoth',
    'Bastet',
    'Sekhmet',
    'Set',
    'Amun',
    'Nut',
    'Maat',
    'Ptah',
    'Hathor',
    'Anhur',
    'Khnum',
    'Wadjet',
    'Sobek',
    'Bast',
    'Anuket',
  ],
};

const t_polynesian_mythology: Theme = {
  identifier: 'polynesian-mythology',
  name: 'Polynesian Mythology',
  names: [
    'Maui',
    'Tane',
    'Pele',
    'Hina',
    'Kane',
    'Kanaloa',
    'Mahuika',
    'Whiro',
    'Tawhiri',
    'Rongo',
    'Tangaroa',
    'Haumia',
    'Papa',
    'Rangi',
  ],
};

const t_roman_mythology: Theme = {
  identifier: 'roman-mythology',
  name: 'Roman Mythology',
  names: [
    'Jupiter',
    'Juno',
    'Neptune',
    'Minerva',
    'Mars',
    'Venus',
    'Apollo',
    'Diana',
    'Mercury',
    'Vulcan',
    'Ceres',
    'Bacchus',
    'Proserpina',
    'Pluto',
    'Vesta',
    'Aeneas',
    'Remus',
    'Romulus',
    'Cupid',
    'Faunus',
    'Janus',
    'Juturna',
    'Latona',
    'Lucina',
    'Quirinus',
    'Saturn',
    'Silvanus',
    'Terminus',
    'Ops',
    'Flora',
    'Pomona',
    'Fides',
    'Lares',
    'Manes',
    'Genius',
    'Nona',
    'Decima',
    'Morta',
    'Carmenta',
    'Egeria',
    'Pales',
    'Pax',
    'Victoria',
    'Bellona',
    'Concordia',
    'Liber',
    'Salus',
  ],
};

const c_mythology: Category = {
  name: 'Mythology ⚡',
  language: 'EN',
  bgColor: '#FFC83D',
  themes: [
    t_norse_mythology,
    t_greek_mythology,
    t_egyptian_mythology,
    t_polynesian_mythology,
    t_roman_mythology,
  ],
};

//////////////////////////////////////////////
///////       Locations Category     /////////
//////////////////////////////////////////////

const t_countries: Theme = {
  identifier: 'countries',
  name: 'Countries',
  names: [
    'Japan',
    'Brazil',
    'Canada',
    'Mexico',
    'France',
    'Germany',
    'Italy',
    'Spain',
    'China',
    'India',
    'Russia',
    'Egypt',
    'Greece',
    'Turkey',
    'Norway',
    'Sweden',
    'Denmark',
    'Finland',
    'Iceland',
    'Ireland',
    'Poland',
    'Portugal',
    'Belgium',
    'Austria',
    'Argentina',
    'Chile',
    'Peru',
    'Colombia',
    'Australia',
    'New Zealand',
    'South Korea',
    'Vietnam',
    'Thailand',
    'Indonesia',
    'Malaysia',
    'Singapore',
    'Pakistan',
    'Iran',
    'Iraq',
    'Israel',
    'Jordan',
    'Lebanon',
    'Syria',
    'Kuwait',
    'Qatar',
  ],
};

const t_us_states: Theme = {
  identifier: 'us-states',
  name: 'U.S States',
  names: [
    'California',
    'Texas',
    'Florida',
    'New York',
    'Ohio',
    'Georgia',
    'Michigan',
    'Virginia',
    'Arizona',
    'Tennessee',
    'Indiana',
    'Missouri',
    'Maryland',
    'Wisconsin',
    'Colorado',
    'Minnesota',
    'Alabama',
    'Louisiana',
    'Kentucky',
    'Oregon',
    'Oklahoma',
    'Iowa',
    'Arkansas',
    'Utah',
    'Nevada',
    'Kansas',
    'Nebraska',
    'Idaho',
    'Hawaii',
    'Maine',
    'Montana',
    'Delaware',
    'Vermont',
  ],
};

const t_islands: Theme = {
  identifier: 'islands',
  name: 'Islands',
  names: [
    'Bahamas',
    'Fiji',
    'Hawaii',
    'Jamaica',
    'Bali',
    'Maldives',
    'Samoa',
    'Borneo',
    'Tahiti',
    'Cuba',
    'Santorini',
    'Corsica',
    'Sicily',
    'Ibiza',
    'Crete',
    'Malta',
    'Cyprus',
    'Tonga',
    'Lombok',
    'Capri',
    'Rhodes',
    'Aruba',
    'Montserrat',
    'Antigua',
    'Curacao',
    'Martinique',
    'Guadeloupe',
    'Mallorca',
    'Ibiza',
    'Dominica',
    'Grenada',
  ],
};

const t_biomes: Theme = {
  identifier: 'biomes',
  name: 'Biomes',
  names: [
    'Tundra',
    'Ocean',
    'Savannah',
    'Desert',
    'Grassland',
    'Taiga',
    'Rainforest',
    'Marsh',
    'Swamp',
    'Mountain',
    'Forest',
    'Jungle',
    'Steppe',
    'Prairie',
    'Plateau',
    'Canyon',
    'Delta',
    'Mangrove',
    'Lagoon',
    'Fjord',
    'Estuary',
    'Coral Reef',
    'Volcano',
    'Glacier',
    'Atoll',
    'Cave',
    'Oasis',
    'Dune',
    'Cliff',
    'Bayou',
    'Pond',
    'Lake',
    'River',
    'Waterfall',
    'Bluff',
    'Fen',
    'Bog',
    'Moor',
    'Badlands',
    'Crag',
    'Gorge',
    'Hill',
    'Plain',
    'Peninsula',
    'Cove',
    'Channel',
    'Sinkhole',
    'Butte',
  ],
};

const t_cities: Theme = {
  identifier: 'cities',
  name: 'Cities',
  names: [
    'Tokyo',
    'Paris',
    'London',
    'Sydney',
    'Moscow',
    'Berlin',
    'Rome',
    'Dubai',
    'Bangkok',
    'Toronto',
    'Madrid',
    'Seoul',
    'Mumbai',
    'Cairo',
    'Venice',
    'Athens',
    'Lisbon',
    'Prague',
    'Vienna',
    'Amsterdam',
    'Hanoi',
    'Jakarta',
    'Chicago',
    'Shanghai',
    'Beijing',
    'Singapore',
    'Dublin',
    'Lagos',
    'Milan',
    'Lima',
    'Kiev',
    'New York',
    'Los Angeles',
    'San Diego',
    'Boston',
    'Miami',
    'Houston',
    'Dallas',
    'Seattle',
    'Denver',
    'Phoenix',
    'Atlanta',
    'Detroit',
    'Manchester',
    'Liverpool',
    'Bristol',
    'Leeds',
    'York',
    'Oxford',
    'Cambridge',
  ],
};

const t_astrology: Theme = {
  identifier: 'astrology',
  name: 'Astrology',
  names: [
    'Aries',
    'Taurus',
    'Gemini',
    'Cancer',
    'Leo',
    'Virgo',
    'Libra',
    'Scorpio',
    'Capricorn',
    'Aquarius',
    'Pisces',
    'Sun',
    'Moon',
    'Mercury',
    'Venus',
    'Mars',
    'Jupiter',
    'Saturn',
    'Uranus',
    'Neptune',
    'Pluto',
    'Elements',
    'Fire',
    'Earth',
    'Air',
    'Water',
    'Qualities',
    'Cardinal',
    'Fixed',
    'Mutable',
    'Houses',
    'First',
    'Second',
    'Third',
    'Fourth',
    'Fifth',
    'Sixth',
    'Seventh',
    'Eighth',
    'Ninth',
    'Tenth',
    'Eleventh',
    'Twelfth',
    'Aspects',
    'Trine',
    'Square',
    'Opposition',
  ],
};

const c_locations: Category = {
  name: 'Locations 🌋',
  language: 'EN',
  bgColor: '#F7630C',
  themes: [t_countries, t_us_states, t_islands, t_biomes, t_cities, t_astrology],
};

//////////////////////////////////////////////
//////       Human Names Category     ////////
//////////////////////////////////////////////

const t_us_presidents: Theme = {
  identifier: 'us-presidents',
  name: 'U.S Presidents',
  names: [
    'Washington',
    'Adams',
    'Jefferson',
    'Madison',
    'Monroe',
    'Jackson',
    'Van Buren',
    'Harrison',
    'Tyler',
    'Polk',
    'Taylor',
    'Fillmore',
    'Pierce',
    'Buchanan',
    'Lincoln',
    'Grant',
    'Hayes',
    'Garfield',
    'Arthur',
    'Cleveland',
    'Harrison',
    'McKinley',
    'Roosevelt',
    'Taft',
    'Wilson',
    'Harding',
    'Coolidge',
    'Hoover',
    'Truman',
    'Eisenhower',
    'Kennedy',
    'Johnson',
    'Nixon',
    'Ford',
    'Carter',
    'Reagan',
    'Clinton',
    'Bush',
    'Obama',
    'Trump',
    'Biden',
  ],
};

const t_celebrities: Theme = {
  identifier: 'celebrities',
  name: 'Celebrities',
  names: [
    'Elvis',
    'Beyoncé',
    'Madonna',
    'Prince',
    'Cher',
    'Adele',
    'Drake',
    'Ariana',
    'Taylor',
    'Eminem',
    'Rihanna',
    'Shakira',
    'Monroe',
    'Streep',
    'Cruise',
    'Clooney',
    'Denzel',
    'Pitt',
    'Jolie',
    'Depp',
    'Lawrence',
    'DiCaprio',
    'Gaga',
    'Swift',
    'Kanye',
    'Lopez',
    'Bieber',
    'Stallone',
    'Hanks',
    'Perry',
    'Cyrus',
    'Lana',
    'Jolie',
    'Hathaway',
    'Damon',
    'Johansson',
    'Bale',
    'Diaz',
    'Hathaway',
    'Gosling',
    'Phoenix',
    'Kutcher',
    'Kidman',
    'Cavill',
    'Jackman',
    'Fox',
    'Gosling',
  ],
};

const t_historic_figures: Theme = {
  identifier: 'historic-figures',
  name: 'Historic Figures',
  names: [
    'Newton',
    'Galileo',
    'Einstein',
    'Da Vinci',
    'Cleopatra',
    'Napoleon',
    'Gandhi',
    'Lincoln',
    'Churchill',
    'Mozart',
    'Tesla',
    'Columbus',
    'Marie Curie',
    'Socrates',
    'Nelson',
    'Confucius',
    'Plato',
    'Aristotle',
    'Bach',
    'Catherine',
    'Hemingway',
    'Tolkien',
    'Genghis',
    'Voltaire',
    'Washington',
    'Darwin',
    'Alexander',
    'Spartacus',
    'Copernicus',
    'Freud',
    'Rembrandt',
    'Beethoven',
    'Cicero',
    'Marx',
    'Nero',
    'Homer',
    'Pablo',
    'Remus',
    'Pocahontas',
    'Joan of Arc',
    'Attila',
    'Houdini',
    'Euler',
    'Houdini',
  ],
};

const t_athletes: Theme = {
  identifier: 'athletes',
  name: 'Athletes',
  names: [
    'Jordan',
    'Ali',
    'Serena',
    'Federer',
    'Ronaldo',
    'Messi',
    'Tiger Woods',
    'Nadal',
    'Bolt',
    'Pele',
    'Neymar',
    'Beckham',
    'Mia Hamm',
    'Biles',
    'Frazier',
    'Nadia',
    'Rousey',
    'Phelps',
    'Gretzky',
    'Maradona',
    'Senna',
    'Sharapova',
    'Federer',
    'Ginobili',
    'Kobe',
    'Bolt',
    'Nadal',
    'Ali',
    'Brady',
    'Gehrig',
    'Marino',
    'Shaq',
    'Woods',
    'Zidane',
    'Djokovic',
    'Nash',
    'Pele',
    'Cristiano',
    'Magic',
    'Wade',
    'Graf',
    'Rodman',
    'Messi',
    'Curry',
    'Durant',
    'Murray',
  ],
};

const c_human_names: Category = {
  name: 'Human Names 🙋‍♂️',
  language: 'EN',
  bgColor: '#3A96DD',
  themes: [t_us_presidents, t_celebrities, t_historic_figures, t_athletes],
};

//////////////////////////////////////////////
//////////////       All     /////////////////
//////////////////////////////////////////////

export const categories: Category[] = [
  c_misc,
  c_vegetation,
  c_food,
  c_drinks,
  c_mythology,
  c_locations,
  c_human_names,
];

export const themes: ThemesObject = categories.reduce<ThemesObject>((acc, category) => {
  category.themes.forEach((theme) => (acc[theme.identifier] = theme));
  return acc;
}, {});

export type Box = {
  [name: string]: {
    name: string;
    pokemon?: Pokemon;
  };
};

export function getNewBoxFromThemeTemplate(theme: Theme): Box {
  const box: Box = {};
  theme.names.forEach((name) => (box[name] = { name }));
  return box;
}
